/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module async_fifo(wclk, wrst_n, winc, wdata, wfull, awfull, rclk, rrst_n, rinc, rdata, rempty, arempty);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  output arempty;
  output awfull;
  wire [7:0] \fifomem.mem[0] ;
  wire [7:0] \fifomem.mem[1] ;
  wire [7:0] \fifomem.mem[2] ;
  wire [7:0] \fifomem.mem[3] ;
  wire [1:0] \fifomem.raddr ;
  wire [1:0] \fifomem.waddr ;
  input rclk;
  output [7:0] rdata;
  output rempty;
  input rinc;
  wire [2:0] rptr;
  wire \rptr_empty.arempty_val ;
  wire [2:0] \rptr_empty.rbinnext ;
  wire \rptr_empty.rempty_val ;
  wire [2:0] \rptr_empty.rgraynext ;
  wire [2:0] \rptr_empty.rq2_wptr ;
  input rrst_n;
  wire [2:0] \sync_r2w.wq1_rptr ;
  wire [2:0] \sync_r2w.wq2_rptr ;
  wire [2:0] \sync_w2r.rq1_wptr ;
  wire [2:0] \sync_w2r.wptr ;
  input wclk;
  input [7:0] wdata;
  output wfull;
  input winc;
  wire \wptr_full.awfull_val ;
  wire [2:0] \wptr_full.wbinnext ;
  wire \wptr_full.wfull_val ;
  wire [2:0] \wptr_full.wgraynext ;
  input wrst_n;
  sky130_fd_sc_hd__mux4_2 _070_ (
    .A0(\fifomem.mem[0] [0]),
    .A1(\fifomem.mem[2] [0]),
    .A2(\fifomem.mem[1] [0]),
    .A3(\fifomem.mem[3] [0]),
    .S0(\fifomem.raddr [1]),
    .S1(\fifomem.raddr [0]),
    .X(rdata[0])
  );
  sky130_fd_sc_hd__mux4_2 _071_ (
    .A0(\fifomem.mem[0] [1]),
    .A1(\fifomem.mem[2] [1]),
    .A2(\fifomem.mem[1] [1]),
    .A3(\fifomem.mem[3] [1]),
    .S0(\fifomem.raddr [1]),
    .S1(\fifomem.raddr [0]),
    .X(rdata[1])
  );
  sky130_fd_sc_hd__mux4_2 _072_ (
    .A0(\fifomem.mem[0] [2]),
    .A1(\fifomem.mem[2] [2]),
    .A2(\fifomem.mem[1] [2]),
    .A3(\fifomem.mem[3] [2]),
    .S0(\fifomem.raddr [1]),
    .S1(\fifomem.raddr [0]),
    .X(rdata[2])
  );
  sky130_fd_sc_hd__mux4_2 _073_ (
    .A0(\fifomem.mem[0] [3]),
    .A1(\fifomem.mem[2] [3]),
    .A2(\fifomem.mem[1] [3]),
    .A3(\fifomem.mem[3] [3]),
    .S0(\fifomem.raddr [1]),
    .S1(\fifomem.raddr [0]),
    .X(rdata[3])
  );
  sky130_fd_sc_hd__mux4_2 _074_ (
    .A0(\fifomem.mem[0] [4]),
    .A1(\fifomem.mem[2] [4]),
    .A2(\fifomem.mem[1] [4]),
    .A3(\fifomem.mem[3] [4]),
    .S0(\fifomem.raddr [1]),
    .S1(\fifomem.raddr [0]),
    .X(rdata[4])
  );
  sky130_fd_sc_hd__mux4_2 _075_ (
    .A0(\fifomem.mem[0] [5]),
    .A1(\fifomem.mem[2] [5]),
    .A2(\fifomem.mem[1] [5]),
    .A3(\fifomem.mem[3] [5]),
    .S0(\fifomem.raddr [1]),
    .S1(\fifomem.raddr [0]),
    .X(rdata[5])
  );
  sky130_fd_sc_hd__mux4_2 _076_ (
    .A0(\fifomem.mem[0] [6]),
    .A1(\fifomem.mem[1] [6]),
    .A2(\fifomem.mem[2] [6]),
    .A3(\fifomem.mem[3] [6]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(rdata[6])
  );
  sky130_fd_sc_hd__mux4_2 _077_ (
    .A0(\fifomem.mem[0] [7]),
    .A1(\fifomem.mem[1] [7]),
    .A2(\fifomem.mem[2] [7]),
    .A3(\fifomem.mem[3] [7]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(rdata[7])
  );
  sky130_fd_sc_hd__nor4bb_1 _078_ (
    .A(\fifomem.waddr [1]),
    .B(wfull),
    .C_N(winc),
    .D_N(\fifomem.waddr [0]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__mux2_1 _079_ (
    .A0(\fifomem.mem[1] [0]),
    .A1(wdata[0]),
    .S(_035_),
    .X(_008_)
  );
  sky130_fd_sc_hd__mux2_1 _080_ (
    .A0(\fifomem.mem[1] [1]),
    .A1(wdata[1]),
    .S(_035_),
    .X(_009_)
  );
  sky130_fd_sc_hd__mux2_1 _081_ (
    .A0(\fifomem.mem[1] [2]),
    .A1(wdata[2]),
    .S(_035_),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux2_1 _082_ (
    .A0(\fifomem.mem[1] [3]),
    .A1(wdata[3]),
    .S(_035_),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _083_ (
    .A0(\fifomem.mem[1] [4]),
    .A1(wdata[4]),
    .S(_035_),
    .X(_012_)
  );
  sky130_fd_sc_hd__mux2_1 _084_ (
    .A0(\fifomem.mem[1] [5]),
    .A1(wdata[5]),
    .S(_035_),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _085_ (
    .A0(\fifomem.mem[1] [6]),
    .A1(wdata[6]),
    .S(_035_),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux2_1 _086_ (
    .A0(\fifomem.mem[1] [7]),
    .A1(wdata[7]),
    .S(_035_),
    .X(_015_)
  );
  sky130_fd_sc_hd__nor4bb_1 _087_ (
    .A(\fifomem.waddr [0]),
    .B(wfull),
    .C_N(\fifomem.waddr [1]),
    .D_N(winc),
    .Y(_032_)
  );
  sky130_fd_sc_hd__mux2_1 _088_ (
    .A0(\fifomem.mem[2] [0]),
    .A1(wdata[0]),
    .S(_032_),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _089_ (
    .A0(\fifomem.mem[2] [1]),
    .A1(wdata[1]),
    .S(_032_),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _090_ (
    .A0(\fifomem.mem[2] [2]),
    .A1(wdata[2]),
    .S(_032_),
    .X(_018_)
  );
  sky130_fd_sc_hd__mux2_1 _091_ (
    .A0(\fifomem.mem[2] [3]),
    .A1(wdata[3]),
    .S(_032_),
    .X(_019_)
  );
  sky130_fd_sc_hd__mux2_1 _092_ (
    .A0(\fifomem.mem[2] [4]),
    .A1(wdata[4]),
    .S(_032_),
    .X(_020_)
  );
  sky130_fd_sc_hd__mux2_1 _093_ (
    .A0(\fifomem.mem[2] [5]),
    .A1(wdata[5]),
    .S(_032_),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_1 _094_ (
    .A0(\fifomem.mem[2] [6]),
    .A1(wdata[6]),
    .S(_032_),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux2_1 _095_ (
    .A0(\fifomem.mem[2] [7]),
    .A1(wdata[7]),
    .S(_032_),
    .X(_023_)
  );
  sky130_fd_sc_hd__nand4b_1 _096_ (
    .A_N(wfull),
    .B(\fifomem.waddr [1]),
    .C(\fifomem.waddr [0]),
    .D(winc),
    .Y(_033_)
  );
  sky130_fd_sc_hd__mux2_1 _097_ (
    .A0(wdata[0]),
    .A1(\fifomem.mem[3] [0]),
    .S(_033_),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2_1 _098_ (
    .A0(wdata[1]),
    .A1(\fifomem.mem[3] [1]),
    .S(_033_),
    .X(_025_)
  );
  sky130_fd_sc_hd__mux2_1 _099_ (
    .A0(wdata[2]),
    .A1(\fifomem.mem[3] [2]),
    .S(_033_),
    .X(_026_)
  );
  sky130_fd_sc_hd__mux2_1 _100_ (
    .A0(wdata[3]),
    .A1(\fifomem.mem[3] [3]),
    .S(_033_),
    .X(_027_)
  );
  sky130_fd_sc_hd__mux2_1 _101_ (
    .A0(wdata[4]),
    .A1(\fifomem.mem[3] [4]),
    .S(_033_),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2_1 _102_ (
    .A0(wdata[5]),
    .A1(\fifomem.mem[3] [5]),
    .S(_033_),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2_1 _103_ (
    .A0(wdata[6]),
    .A1(\fifomem.mem[3] [6]),
    .S(_033_),
    .X(_030_)
  );
  sky130_fd_sc_hd__mux2_1 _104_ (
    .A0(wdata[7]),
    .A1(\fifomem.mem[3] [7]),
    .S(_033_),
    .X(_031_)
  );
  sky130_fd_sc_hd__nor4b_1 _105_ (
    .A(\fifomem.waddr [0]),
    .B(\fifomem.waddr [1]),
    .C(wfull),
    .D_N(winc),
    .Y(_034_)
  );
  sky130_fd_sc_hd__mux2_1 _106_ (
    .A0(\fifomem.mem[0] [0]),
    .A1(wdata[0]),
    .S(_034_),
    .X(_000_)
  );
  sky130_fd_sc_hd__mux2_1 _107_ (
    .A0(\fifomem.mem[0] [1]),
    .A1(wdata[1]),
    .S(_034_),
    .X(_001_)
  );
  sky130_fd_sc_hd__mux2_1 _108_ (
    .A0(\fifomem.mem[0] [2]),
    .A1(wdata[2]),
    .S(_034_),
    .X(_002_)
  );
  sky130_fd_sc_hd__mux2_1 _109_ (
    .A0(\fifomem.mem[0] [3]),
    .A1(wdata[3]),
    .S(_034_),
    .X(_003_)
  );
  sky130_fd_sc_hd__mux2_1 _110_ (
    .A0(\fifomem.mem[0] [4]),
    .A1(wdata[4]),
    .S(_034_),
    .X(_004_)
  );
  sky130_fd_sc_hd__mux2_1 _111_ (
    .A0(\fifomem.mem[0] [5]),
    .A1(wdata[5]),
    .S(_034_),
    .X(_005_)
  );
  sky130_fd_sc_hd__mux2_1 _112_ (
    .A0(\fifomem.mem[0] [6]),
    .A1(wdata[6]),
    .S(_034_),
    .X(_006_)
  );
  sky130_fd_sc_hd__mux2_1 _113_ (
    .A0(\fifomem.mem[0] [7]),
    .A1(wdata[7]),
    .S(_034_),
    .X(_007_)
  );
  sky130_fd_sc_hd__dfxtp_1 _114_ (
    .CLK(wclk),
    .D(_024_),
    .Q(\fifomem.mem[3] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _115_ (
    .CLK(wclk),
    .D(_025_),
    .Q(\fifomem.mem[3] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _116_ (
    .CLK(wclk),
    .D(_026_),
    .Q(\fifomem.mem[3] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _117_ (
    .CLK(wclk),
    .D(_027_),
    .Q(\fifomem.mem[3] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _118_ (
    .CLK(wclk),
    .D(_028_),
    .Q(\fifomem.mem[3] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _119_ (
    .CLK(wclk),
    .D(_029_),
    .Q(\fifomem.mem[3] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _120_ (
    .CLK(wclk),
    .D(_030_),
    .Q(\fifomem.mem[3] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _121_ (
    .CLK(wclk),
    .D(_031_),
    .Q(\fifomem.mem[3] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _122_ (
    .CLK(wclk),
    .D(_016_),
    .Q(\fifomem.mem[2] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _123_ (
    .CLK(wclk),
    .D(_017_),
    .Q(\fifomem.mem[2] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _124_ (
    .CLK(wclk),
    .D(_018_),
    .Q(\fifomem.mem[2] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _125_ (
    .CLK(wclk),
    .D(_019_),
    .Q(\fifomem.mem[2] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _126_ (
    .CLK(wclk),
    .D(_020_),
    .Q(\fifomem.mem[2] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _127_ (
    .CLK(wclk),
    .D(_021_),
    .Q(\fifomem.mem[2] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _128_ (
    .CLK(wclk),
    .D(_022_),
    .Q(\fifomem.mem[2] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _129_ (
    .CLK(wclk),
    .D(_023_),
    .Q(\fifomem.mem[2] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _130_ (
    .CLK(wclk),
    .D(_008_),
    .Q(\fifomem.mem[1] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _131_ (
    .CLK(wclk),
    .D(_009_),
    .Q(\fifomem.mem[1] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _132_ (
    .CLK(wclk),
    .D(_010_),
    .Q(\fifomem.mem[1] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _133_ (
    .CLK(wclk),
    .D(_011_),
    .Q(\fifomem.mem[1] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _134_ (
    .CLK(wclk),
    .D(_012_),
    .Q(\fifomem.mem[1] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _135_ (
    .CLK(wclk),
    .D(_013_),
    .Q(\fifomem.mem[1] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _136_ (
    .CLK(wclk),
    .D(_014_),
    .Q(\fifomem.mem[1] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _137_ (
    .CLK(wclk),
    .D(_015_),
    .Q(\fifomem.mem[1] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _138_ (
    .CLK(wclk),
    .D(_000_),
    .Q(\fifomem.mem[0] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _139_ (
    .CLK(wclk),
    .D(_001_),
    .Q(\fifomem.mem[0] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _140_ (
    .CLK(wclk),
    .D(_002_),
    .Q(\fifomem.mem[0] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _141_ (
    .CLK(wclk),
    .D(_003_),
    .Q(\fifomem.mem[0] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _142_ (
    .CLK(wclk),
    .D(_004_),
    .Q(\fifomem.mem[0] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _143_ (
    .CLK(wclk),
    .D(_005_),
    .Q(\fifomem.mem[0] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _144_ (
    .CLK(wclk),
    .D(_006_),
    .Q(\fifomem.mem[0] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _145_ (
    .CLK(wclk),
    .D(_007_),
    .Q(\fifomem.mem[0] [7])
  );
  sky130_fd_sc_hd__nand2b_1 _146_ (
    .A_N(rempty),
    .B(rinc),
    .Y(_036_)
  );
  sky130_fd_sc_hd__and3b_1 _147_ (
    .A_N(rempty),
    .B(rinc),
    .C(\fifomem.raddr [0]),
    .X(_037_)
  );
  sky130_fd_sc_hd__xnor2_1 _148_ (
    .A(\fifomem.raddr [0]),
    .B(_036_),
    .Y(\rptr_empty.rbinnext [0])
  );
  sky130_fd_sc_hd__nand4b_1 _149_ (
    .A_N(rempty),
    .B(rinc),
    .C(\fifomem.raddr [0]),
    .D(\fifomem.raddr [1]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nor2_1 _150_ (
    .A(\fifomem.raddr [1]),
    .B(_037_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__xor2_1 _151_ (
    .A(\fifomem.raddr [1]),
    .B(_037_),
    .X(\rptr_empty.rbinnext [1])
  );
  sky130_fd_sc_hd__xnor2_1 _152_ (
    .A(\rptr_empty.rq2_wptr [0]),
    .B(\rptr_empty.rbinnext [1]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__xnor2_1 _153_ (
    .A(\rptr_empty.rbinnext [0]),
    .B(_040_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__xor2_1 _154_ (
    .A(rptr[2]),
    .B(_038_),
    .X(_042_)
  );
  sky130_fd_sc_hd__clkinv_1 _155_ (
    .A(_042_),
    .Y(\rptr_empty.rbinnext [2])
  );
  sky130_fd_sc_hd__xnor2_1 _156_ (
    .A(\rptr_empty.rq2_wptr [2]),
    .B(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__xnor2_1 _157_ (
    .A(rptr[2]),
    .B(_039_),
    .Y(\rptr_empty.rgraynext [1])
  );
  sky130_fd_sc_hd__xor2_1 _158_ (
    .A(\rptr_empty.rq2_wptr [1]),
    .B(\rptr_empty.rgraynext [1]),
    .X(_044_)
  );
  sky130_fd_sc_hd__nor3_1 _159_ (
    .A(_041_),
    .B(_043_),
    .C(_044_),
    .Y(\rptr_empty.rempty_val )
  );
  sky130_fd_sc_hd__and3_1 _160_ (
    .A(\fifomem.raddr [1]),
    .B(rptr[2]),
    .C(\rptr_empty.rbinnext [0]),
    .X(_045_)
  );
  sky130_fd_sc_hd__a21oi_1 _161_ (
    .A1(\fifomem.raddr [1]),
    .A2(\rptr_empty.rbinnext [0]),
    .B1(\rptr_empty.rbinnext [2]),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nor2_1 _162_ (
    .A(_045_),
    .B(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__xnor2_1 _163_ (
    .A(\rptr_empty.rbinnext [0]),
    .B(\rptr_empty.rbinnext [1]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__clkinv_1 _164_ (
    .A(_048_),
    .Y(\rptr_empty.rgraynext [0])
  );
  sky130_fd_sc_hd__o21a_1 _165_ (
    .A1(_045_),
    .A2(_046_),
    .B1(_048_),
    .X(_049_)
  );
  sky130_fd_sc_hd__nor2_1 _166_ (
    .A(_042_),
    .B(_048_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__o21ai_0 _167_ (
    .A1(_049_),
    .A2(_050_),
    .B1(\rptr_empty.rq2_wptr [1]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__xor2_1 _168_ (
    .A(\rptr_empty.rq2_wptr [2]),
    .B(_047_),
    .X(_052_)
  );
  sky130_fd_sc_hd__nor3_1 _169_ (
    .A(\rptr_empty.rq2_wptr [1]),
    .B(_049_),
    .C(_050_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nor4b_1 _170_ (
    .A(_040_),
    .B(_052_),
    .C(_053_),
    .D_N(_051_),
    .Y(\rptr_empty.arempty_val )
  );
  sky130_fd_sc_hd__dfrtp_1 _171_ (
    .CLK(rclk),
    .D(\rptr_empty.rbinnext [0]),
    .Q(\fifomem.raddr [0]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _172_ (
    .CLK(rclk),
    .D(\rptr_empty.rbinnext [1]),
    .Q(\fifomem.raddr [1]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _173_ (
    .CLK(rclk),
    .D(\rptr_empty.rgraynext [0]),
    .Q(rptr[0]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _174_ (
    .CLK(rclk),
    .D(\rptr_empty.rgraynext [1]),
    .Q(rptr[1]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _175_ (
    .CLK(rclk),
    .D(\rptr_empty.rbinnext [2]),
    .Q(rptr[2]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _176_ (
    .CLK(rclk),
    .D(\rptr_empty.rempty_val ),
    .Q(rempty),
    .SET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _177_ (
    .CLK(rclk),
    .D(\rptr_empty.arempty_val ),
    .Q(arempty),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _178_ (
    .CLK(wclk),
    .D(rptr[0]),
    .Q(\sync_r2w.wq1_rptr [0]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _179_ (
    .CLK(wclk),
    .D(rptr[1]),
    .Q(\sync_r2w.wq1_rptr [1]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _180_ (
    .CLK(wclk),
    .D(rptr[2]),
    .Q(\sync_r2w.wq1_rptr [2]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _181_ (
    .CLK(wclk),
    .D(\sync_r2w.wq1_rptr [0]),
    .Q(\sync_r2w.wq2_rptr [0]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _182_ (
    .CLK(wclk),
    .D(\sync_r2w.wq1_rptr [1]),
    .Q(\sync_r2w.wq2_rptr [1]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _183_ (
    .CLK(wclk),
    .D(\sync_r2w.wq1_rptr [2]),
    .Q(\sync_r2w.wq2_rptr [2]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _184_ (
    .CLK(rclk),
    .D(\sync_w2r.wptr [0]),
    .Q(\sync_w2r.rq1_wptr [0]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _185_ (
    .CLK(rclk),
    .D(\sync_w2r.wptr [1]),
    .Q(\sync_w2r.rq1_wptr [1]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _186_ (
    .CLK(rclk),
    .D(\sync_w2r.wptr [2]),
    .Q(\sync_w2r.rq1_wptr [2]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _187_ (
    .CLK(rclk),
    .D(\sync_w2r.rq1_wptr [0]),
    .Q(\rptr_empty.rq2_wptr [0]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _188_ (
    .CLK(rclk),
    .D(\sync_w2r.rq1_wptr [1]),
    .Q(\rptr_empty.rq2_wptr [1]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _189_ (
    .CLK(rclk),
    .D(\sync_w2r.rq1_wptr [2]),
    .Q(\rptr_empty.rq2_wptr [2]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__nand2b_1 _190_ (
    .A_N(wfull),
    .B(winc),
    .Y(_054_)
  );
  sky130_fd_sc_hd__and3b_1 _191_ (
    .A_N(wfull),
    .B(winc),
    .C(\fifomem.waddr [0]),
    .X(_055_)
  );
  sky130_fd_sc_hd__xnor2_1 _192_ (
    .A(\fifomem.waddr [0]),
    .B(_054_),
    .Y(\wptr_full.wbinnext [0])
  );
  sky130_fd_sc_hd__nand4b_1 _193_ (
    .A_N(wfull),
    .B(winc),
    .C(\fifomem.waddr [0]),
    .D(\fifomem.waddr [1]),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nor2_1 _194_ (
    .A(\fifomem.waddr [1]),
    .B(_055_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__xor2_1 _195_ (
    .A(\fifomem.waddr [1]),
    .B(_055_),
    .X(\wptr_full.wbinnext [1])
  );
  sky130_fd_sc_hd__xnor2_1 _196_ (
    .A(\sync_r2w.wq2_rptr [0]),
    .B(\wptr_full.wbinnext [1]),
    .Y(_058_)
  );
  sky130_fd_sc_hd__xnor2_1 _197_ (
    .A(\wptr_full.wbinnext [0]),
    .B(_058_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__xnor2_1 _198_ (
    .A(\sync_w2r.wptr [2]),
    .B(_056_),
    .Y(\wptr_full.wbinnext [2])
  );
  sky130_fd_sc_hd__xnor2_1 _199_ (
    .A(\sync_r2w.wq2_rptr [2]),
    .B(\wptr_full.wbinnext [2]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__xnor2_1 _200_ (
    .A(\sync_w2r.wptr [2]),
    .B(_057_),
    .Y(\wptr_full.wgraynext [1])
  );
  sky130_fd_sc_hd__xnor2_1 _201_ (
    .A(\sync_r2w.wq2_rptr [1]),
    .B(\wptr_full.wgraynext [1]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nor3_1 _202_ (
    .A(_059_),
    .B(_060_),
    .C(_061_),
    .Y(\wptr_full.wfull_val )
  );
  sky130_fd_sc_hd__nand3_1 _203_ (
    .A(\fifomem.waddr [1]),
    .B(\sync_w2r.wptr [2]),
    .C(\wptr_full.wbinnext [0]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__a21o_1 _204_ (
    .A1(\fifomem.waddr [1]),
    .A2(\wptr_full.wbinnext [0]),
    .B1(\wptr_full.wbinnext [2]),
    .X(_063_)
  );
  sky130_fd_sc_hd__xor2_1 _205_ (
    .A(\wptr_full.wbinnext [0]),
    .B(\wptr_full.wbinnext [1]),
    .X(\wptr_full.wgraynext [0])
  );
  sky130_fd_sc_hd__a21o_1 _206_ (
    .A1(_062_),
    .A2(_063_),
    .B1(\wptr_full.wgraynext [0]),
    .X(_064_)
  );
  sky130_fd_sc_hd__nand2_1 _207_ (
    .A(\wptr_full.wbinnext [2]),
    .B(\wptr_full.wgraynext [0]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__a21oi_1 _208_ (
    .A1(_064_),
    .A2(_065_),
    .B1(\sync_r2w.wq2_rptr [1]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__a21oi_1 _209_ (
    .A1(_062_),
    .A2(_063_),
    .B1(\sync_r2w.wq2_rptr [2]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__a31oi_1 _210_ (
    .A1(\sync_r2w.wq2_rptr [2]),
    .A2(_062_),
    .A3(_063_),
    .B1(_058_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand3_1 _211_ (
    .A(\sync_r2w.wq2_rptr [1]),
    .B(_064_),
    .C(_065_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nor4bb_1 _212_ (
    .A(_066_),
    .B(_067_),
    .C_N(_068_),
    .D_N(_069_),
    .Y(\wptr_full.awfull_val )
  );
  sky130_fd_sc_hd__dfrtp_1 _213_ (
    .CLK(wclk),
    .D(\wptr_full.wbinnext [0]),
    .Q(\fifomem.waddr [0]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _214_ (
    .CLK(wclk),
    .D(\wptr_full.wbinnext [1]),
    .Q(\fifomem.waddr [1]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _215_ (
    .CLK(wclk),
    .D(\wptr_full.wgraynext [0]),
    .Q(\sync_w2r.wptr [0]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _216_ (
    .CLK(wclk),
    .D(\wptr_full.wgraynext [1]),
    .Q(\sync_w2r.wptr [1]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _217_ (
    .CLK(wclk),
    .D(\wptr_full.wbinnext [2]),
    .Q(\sync_w2r.wptr [2]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _218_ (
    .CLK(wclk),
    .D(\wptr_full.wfull_val ),
    .Q(wfull),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _219_ (
    .CLK(wclk),
    .D(\wptr_full.awfull_val ),
    .Q(awfull),
    .RESET_B(wrst_n)
  );
  assign \wptr_full.wgraynext [2] = \wptr_full.wbinnext [2];
  assign \rptr_empty.rgraynext [2] = \rptr_empty.rbinnext [2];
endmodule
