/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module system_async_fifo_top(wclk_raw, rclk_raw, wrst_n, rrst_n, w_event, r_event, rdata_o, rempty_o, arempty_o, wfull_o, awfull_o);
  wire [4:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire [4:0] _275_;
  wire _276_;
  wire [7:0] _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  output arempty_o;
  output awfull_o;
  wire cons_active;
  wire prod_active;
  input r_event;
  input rclk_raw;
  output [7:0] rdata_o;
  output rempty_o;
  wire rinc;
  input rrst_n;
  wire [4:0] \u_cons.burst_cnt ;
  wire [7:0] \u_fifo.fifomem.mem[0] ;
  wire [7:0] \u_fifo.fifomem.mem[10] ;
  wire [7:0] \u_fifo.fifomem.mem[11] ;
  wire [7:0] \u_fifo.fifomem.mem[12] ;
  wire [7:0] \u_fifo.fifomem.mem[13] ;
  wire [7:0] \u_fifo.fifomem.mem[14] ;
  wire [7:0] \u_fifo.fifomem.mem[15] ;
  wire [7:0] \u_fifo.fifomem.mem[1] ;
  wire [7:0] \u_fifo.fifomem.mem[2] ;
  wire [7:0] \u_fifo.fifomem.mem[3] ;
  wire [7:0] \u_fifo.fifomem.mem[4] ;
  wire [7:0] \u_fifo.fifomem.mem[5] ;
  wire [7:0] \u_fifo.fifomem.mem[6] ;
  wire [7:0] \u_fifo.fifomem.mem[7] ;
  wire [7:0] \u_fifo.fifomem.mem[8] ;
  wire [7:0] \u_fifo.fifomem.mem[9] ;
  wire [3:0] \u_fifo.fifomem.raddr ;
  wire [3:0] \u_fifo.fifomem.waddr ;
  wire \u_fifo.fifomem.wclken ;
  wire [7:0] \u_fifo.fifomem.wdata ;
  wire [4:0] \u_fifo.rptr ;
  wire \u_fifo.rptr_empty.arempty_val ;
  wire [4:0] \u_fifo.rptr_empty.rbinnext ;
  wire \u_fifo.rptr_empty.rempty_val ;
  wire [4:0] \u_fifo.rptr_empty.rgraynext ;
  wire [4:0] \u_fifo.rptr_empty.rq2_wptr ;
  wire [4:0] \u_fifo.sync_r2w.wq1_rptr ;
  wire [4:0] \u_fifo.sync_r2w.wq2_rptr ;
  wire [4:0] \u_fifo.sync_w2r.rq1_wptr ;
  wire [4:0] \u_fifo.sync_w2r.wptr ;
  wire \u_fifo.wptr_full.awfull_val ;
  wire [4:0] \u_fifo.wptr_full.wbinnext ;
  wire \u_fifo.wptr_full.wfull_val ;
  wire [4:0] \u_fifo.wptr_full.wgraynext ;
  wire [4:0] \u_prod.burst_cnt ;
  input w_event;
  input wclk_raw;
  output wfull_o;
  input wrst_n;
  sky130_fd_sc_hd__clkinv_1 _298_ (
    .A(cons_active),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nor2b_1 _299_ (
    .A(rempty_o),
    .B_N(cons_active),
    .Y(_002_)
  );
  sky130_fd_sc_hd__or3_1 _300_ (
    .A(prod_active),
    .B(rempty_o),
    .C(cons_active),
    .X(_004_)
  );
  sky130_fd_sc_hd__and2_0 _301_ (
    .A(\u_cons.burst_cnt [0]),
    .B(\u_cons.burst_cnt [1]),
    .X(_005_)
  );
  sky130_fd_sc_hd__nand4_1 _302_ (
    .A(\u_cons.burst_cnt [0]),
    .B(\u_cons.burst_cnt [1]),
    .C(\u_cons.burst_cnt [2]),
    .D(\u_cons.burst_cnt [3]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__o21ai_0 _303_ (
    .A1(\u_cons.burst_cnt [4]),
    .A2(_006_),
    .B1(_002_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nand2_1 _304_ (
    .A(_004_),
    .B(_007_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__o211ai_1 _305_ (
    .A1(\u_cons.burst_cnt [4]),
    .A2(_006_),
    .B1(_002_),
    .C1(\u_cons.burst_cnt [0]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nand2_1 _306_ (
    .A(\u_cons.burst_cnt [0]),
    .B(_004_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__a21boi_0 _307_ (
    .A1(_007_),
    .A2(_009_),
    .B1_N(_008_),
    .Y(_000_[0])
  );
  sky130_fd_sc_hd__nand2_1 _308_ (
    .A(\u_cons.burst_cnt [1]),
    .B(_004_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__o211ai_1 _309_ (
    .A1(\u_cons.burst_cnt [4]),
    .A2(_006_),
    .B1(_005_),
    .C1(_002_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__a21boi_0 _310_ (
    .A1(_008_),
    .A2(_010_),
    .B1_N(_011_),
    .Y(_000_[1])
  );
  sky130_fd_sc_hd__nand2_1 _311_ (
    .A(\u_cons.burst_cnt [2]),
    .B(_004_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__o2111ai_1 _312_ (
    .A1(\u_cons.burst_cnt [4]),
    .A2(_006_),
    .B1(_005_),
    .C1(_002_),
    .D1(\u_cons.burst_cnt [2]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__a21boi_0 _313_ (
    .A1(_011_),
    .A2(_012_),
    .B1_N(_013_),
    .Y(_000_[2])
  );
  sky130_fd_sc_hd__nand2_1 _314_ (
    .A(\u_cons.burst_cnt [3]),
    .B(_004_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__mux2i_1 _315_ (
    .A0(\u_cons.burst_cnt [3]),
    .A1(_014_),
    .S(_013_),
    .Y(_000_[3])
  );
  sky130_fd_sc_hd__o311a_1 _316_ (
    .A1(rempty_o),
    .A2(_003_),
    .A3(_006_),
    .B1(_004_),
    .C1(\u_cons.burst_cnt [4]),
    .X(_000_[4])
  );
  sky130_fd_sc_hd__dfrtp_1 _317_ (
    .CLK(rclk_raw),
    .D(_001_),
    .Q(cons_active),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _318_ (
    .CLK(rclk_raw),
    .D(_002_),
    .Q(rinc),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _319_ (
    .CLK(rclk_raw),
    .D(_000_[0]),
    .Q(\u_cons.burst_cnt [0]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _320_ (
    .CLK(rclk_raw),
    .D(_000_[1]),
    .Q(\u_cons.burst_cnt [1]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _321_ (
    .CLK(rclk_raw),
    .D(_000_[2]),
    .Q(\u_cons.burst_cnt [2]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _322_ (
    .CLK(rclk_raw),
    .D(_000_[3]),
    .Q(\u_cons.burst_cnt [3]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _323_ (
    .CLK(rclk_raw),
    .D(_000_[4]),
    .Q(\u_cons.burst_cnt [4]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__nor2b_1 _324_ (
    .A(wfull_o),
    .B_N(\u_fifo.fifomem.wclken ),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nand2_1 _325_ (
    .A(\u_fifo.fifomem.waddr [1]),
    .B(_143_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__and3b_1 _326_ (
    .A_N(\u_fifo.fifomem.waddr [0]),
    .B(\u_fifo.fifomem.waddr [1]),
    .C(_143_),
    .X(_145_)
  );
  sky130_fd_sc_hd__nand2_1 _327_ (
    .A(\u_fifo.fifomem.waddr [3]),
    .B(_143_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__and3b_1 _328_ (
    .A_N(\u_fifo.fifomem.waddr [2]),
    .B(\u_fifo.fifomem.waddr [3]),
    .C(_143_),
    .X(_147_)
  );
  sky130_fd_sc_hd__nand2_1 _329_ (
    .A(_145_),
    .B(_147_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__and2_0 _330_ (
    .A(\u_fifo.fifomem.wdata [0]),
    .B(_143_),
    .X(_149_)
  );
  sky130_fd_sc_hd__mux2_1 _331_ (
    .A0(_149_),
    .A1(\u_fifo.fifomem.mem[10] [0]),
    .S(_148_),
    .X(_023_)
  );
  sky130_fd_sc_hd__and2_0 _332_ (
    .A(\u_fifo.fifomem.wdata [1]),
    .B(_143_),
    .X(_150_)
  );
  sky130_fd_sc_hd__mux2_1 _333_ (
    .A0(_150_),
    .A1(\u_fifo.fifomem.mem[10] [1]),
    .S(_148_),
    .X(_024_)
  );
  sky130_fd_sc_hd__and2_0 _334_ (
    .A(\u_fifo.fifomem.wdata [2]),
    .B(_143_),
    .X(_151_)
  );
  sky130_fd_sc_hd__mux2_1 _335_ (
    .A0(_151_),
    .A1(\u_fifo.fifomem.mem[10] [2]),
    .S(_148_),
    .X(_025_)
  );
  sky130_fd_sc_hd__and2_0 _336_ (
    .A(\u_fifo.fifomem.wdata [3]),
    .B(_143_),
    .X(_152_)
  );
  sky130_fd_sc_hd__mux2_1 _337_ (
    .A0(_152_),
    .A1(\u_fifo.fifomem.mem[10] [3]),
    .S(_148_),
    .X(_026_)
  );
  sky130_fd_sc_hd__and2_0 _338_ (
    .A(\u_fifo.fifomem.wdata [4]),
    .B(_143_),
    .X(_153_)
  );
  sky130_fd_sc_hd__mux2_1 _339_ (
    .A0(_153_),
    .A1(\u_fifo.fifomem.mem[10] [4]),
    .S(_148_),
    .X(_027_)
  );
  sky130_fd_sc_hd__and2_0 _340_ (
    .A(\u_fifo.fifomem.wdata [5]),
    .B(_143_),
    .X(_154_)
  );
  sky130_fd_sc_hd__mux2_1 _341_ (
    .A0(_154_),
    .A1(\u_fifo.fifomem.mem[10] [5]),
    .S(_148_),
    .X(_028_)
  );
  sky130_fd_sc_hd__and2_0 _342_ (
    .A(\u_fifo.fifomem.wdata [6]),
    .B(_143_),
    .X(_155_)
  );
  sky130_fd_sc_hd__mux2_1 _343_ (
    .A0(_155_),
    .A1(\u_fifo.fifomem.mem[10] [6]),
    .S(_148_),
    .X(_029_)
  );
  sky130_fd_sc_hd__and2_0 _344_ (
    .A(\u_fifo.fifomem.wdata [7]),
    .B(_143_),
    .X(_156_)
  );
  sky130_fd_sc_hd__mux2_1 _345_ (
    .A0(_156_),
    .A1(\u_fifo.fifomem.mem[10] [7]),
    .S(_148_),
    .X(_030_)
  );
  sky130_fd_sc_hd__nand2_1 _346_ (
    .A(\u_fifo.fifomem.waddr [0]),
    .B(_143_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__and3b_1 _347_ (
    .A_N(\u_fifo.fifomem.waddr [1]),
    .B(_143_),
    .C(\u_fifo.fifomem.waddr [0]),
    .X(_158_)
  );
  sky130_fd_sc_hd__nand2_1 _348_ (
    .A(_147_),
    .B(_158_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__mux2_1 _349_ (
    .A0(_149_),
    .A1(\u_fifo.fifomem.mem[9] [0]),
    .S(_159_),
    .X(_135_)
  );
  sky130_fd_sc_hd__mux2_1 _350_ (
    .A0(_150_),
    .A1(\u_fifo.fifomem.mem[9] [1]),
    .S(_159_),
    .X(_136_)
  );
  sky130_fd_sc_hd__mux2_1 _351_ (
    .A0(_151_),
    .A1(\u_fifo.fifomem.mem[9] [2]),
    .S(_159_),
    .X(_137_)
  );
  sky130_fd_sc_hd__mux2_1 _352_ (
    .A0(_152_),
    .A1(\u_fifo.fifomem.mem[9] [3]),
    .S(_159_),
    .X(_138_)
  );
  sky130_fd_sc_hd__mux2_1 _353_ (
    .A0(_153_),
    .A1(\u_fifo.fifomem.mem[9] [4]),
    .S(_159_),
    .X(_139_)
  );
  sky130_fd_sc_hd__mux2_1 _354_ (
    .A0(_154_),
    .A1(\u_fifo.fifomem.mem[9] [5]),
    .S(_159_),
    .X(_140_)
  );
  sky130_fd_sc_hd__mux2_1 _355_ (
    .A0(_155_),
    .A1(\u_fifo.fifomem.mem[9] [6]),
    .S(_159_),
    .X(_141_)
  );
  sky130_fd_sc_hd__mux2_1 _356_ (
    .A0(_156_),
    .A1(\u_fifo.fifomem.mem[9] [7]),
    .S(_159_),
    .X(_142_)
  );
  sky130_fd_sc_hd__o21ai_0 _357_ (
    .A1(\u_fifo.fifomem.waddr [0]),
    .A2(\u_fifo.fifomem.waddr [1]),
    .B1(_143_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__nand2_1 _358_ (
    .A(_147_),
    .B(_160_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__mux2_1 _359_ (
    .A0(_149_),
    .A1(\u_fifo.fifomem.mem[8] [0]),
    .S(_161_),
    .X(_127_)
  );
  sky130_fd_sc_hd__mux2_1 _360_ (
    .A0(_150_),
    .A1(\u_fifo.fifomem.mem[8] [1]),
    .S(_161_),
    .X(_128_)
  );
  sky130_fd_sc_hd__mux2_1 _361_ (
    .A0(_151_),
    .A1(\u_fifo.fifomem.mem[8] [2]),
    .S(_161_),
    .X(_129_)
  );
  sky130_fd_sc_hd__mux2_1 _362_ (
    .A0(_152_),
    .A1(\u_fifo.fifomem.mem[8] [3]),
    .S(_161_),
    .X(_130_)
  );
  sky130_fd_sc_hd__mux2_1 _363_ (
    .A0(_153_),
    .A1(\u_fifo.fifomem.mem[8] [4]),
    .S(_161_),
    .X(_131_)
  );
  sky130_fd_sc_hd__mux2_1 _364_ (
    .A0(_154_),
    .A1(\u_fifo.fifomem.mem[8] [5]),
    .S(_161_),
    .X(_132_)
  );
  sky130_fd_sc_hd__mux2_1 _365_ (
    .A0(_155_),
    .A1(\u_fifo.fifomem.mem[8] [6]),
    .S(_161_),
    .X(_133_)
  );
  sky130_fd_sc_hd__mux2_1 _366_ (
    .A0(_156_),
    .A1(\u_fifo.fifomem.mem[8] [7]),
    .S(_161_),
    .X(_134_)
  );
  sky130_fd_sc_hd__nand3_1 _367_ (
    .A(\u_fifo.fifomem.waddr [0]),
    .B(\u_fifo.fifomem.waddr [1]),
    .C(_143_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nor3_1 _368_ (
    .A(\u_fifo.fifomem.waddr [2]),
    .B(_146_),
    .C(_162_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__mux2_1 _369_ (
    .A0(\u_fifo.fifomem.mem[11] [0]),
    .A1(_149_),
    .S(_163_),
    .X(_031_)
  );
  sky130_fd_sc_hd__mux2_1 _370_ (
    .A0(\u_fifo.fifomem.mem[11] [1]),
    .A1(_150_),
    .S(_163_),
    .X(_032_)
  );
  sky130_fd_sc_hd__mux2_1 _371_ (
    .A0(\u_fifo.fifomem.mem[11] [2]),
    .A1(_151_),
    .S(_163_),
    .X(_033_)
  );
  sky130_fd_sc_hd__mux2_1 _372_ (
    .A0(\u_fifo.fifomem.mem[11] [3]),
    .A1(_152_),
    .S(_163_),
    .X(_034_)
  );
  sky130_fd_sc_hd__mux2_1 _373_ (
    .A0(\u_fifo.fifomem.mem[11] [4]),
    .A1(_153_),
    .S(_163_),
    .X(_035_)
  );
  sky130_fd_sc_hd__mux2_1 _374_ (
    .A0(\u_fifo.fifomem.mem[11] [5]),
    .A1(_154_),
    .S(_163_),
    .X(_036_)
  );
  sky130_fd_sc_hd__mux2_1 _375_ (
    .A0(\u_fifo.fifomem.mem[11] [6]),
    .A1(_155_),
    .S(_163_),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2_1 _376_ (
    .A0(\u_fifo.fifomem.mem[11] [7]),
    .A1(_156_),
    .S(_163_),
    .X(_038_)
  );
  sky130_fd_sc_hd__nand3_1 _377_ (
    .A(\u_fifo.fifomem.waddr [2]),
    .B(\u_fifo.fifomem.waddr [3]),
    .C(_143_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nor3_1 _378_ (
    .A(\u_fifo.fifomem.waddr [1]),
    .B(_157_),
    .C(_164_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__mux2_1 _379_ (
    .A0(\u_fifo.fifomem.mem[13] [0]),
    .A1(_149_),
    .S(_165_),
    .X(_047_)
  );
  sky130_fd_sc_hd__mux2_1 _380_ (
    .A0(\u_fifo.fifomem.mem[13] [1]),
    .A1(_150_),
    .S(_165_),
    .X(_048_)
  );
  sky130_fd_sc_hd__mux2_1 _381_ (
    .A0(\u_fifo.fifomem.mem[13] [2]),
    .A1(_151_),
    .S(_165_),
    .X(_049_)
  );
  sky130_fd_sc_hd__mux2_1 _382_ (
    .A0(\u_fifo.fifomem.mem[13] [3]),
    .A1(_152_),
    .S(_165_),
    .X(_050_)
  );
  sky130_fd_sc_hd__mux2_1 _383_ (
    .A0(\u_fifo.fifomem.mem[13] [4]),
    .A1(_153_),
    .S(_165_),
    .X(_051_)
  );
  sky130_fd_sc_hd__mux2_1 _384_ (
    .A0(\u_fifo.fifomem.mem[13] [5]),
    .A1(_154_),
    .S(_165_),
    .X(_052_)
  );
  sky130_fd_sc_hd__mux2_1 _385_ (
    .A0(\u_fifo.fifomem.mem[13] [6]),
    .A1(_155_),
    .S(_165_),
    .X(_053_)
  );
  sky130_fd_sc_hd__mux2_1 _386_ (
    .A0(\u_fifo.fifomem.mem[13] [7]),
    .A1(_156_),
    .S(_165_),
    .X(_054_)
  );
  sky130_fd_sc_hd__nor2_1 _387_ (
    .A(_162_),
    .B(_164_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__mux2_1 _388_ (
    .A0(\u_fifo.fifomem.mem[15] [0]),
    .A1(_149_),
    .S(_166_),
    .X(_063_)
  );
  sky130_fd_sc_hd__mux2_1 _389_ (
    .A0(\u_fifo.fifomem.mem[15] [1]),
    .A1(_150_),
    .S(_166_),
    .X(_064_)
  );
  sky130_fd_sc_hd__mux2_1 _390_ (
    .A0(\u_fifo.fifomem.mem[15] [2]),
    .A1(_151_),
    .S(_166_),
    .X(_065_)
  );
  sky130_fd_sc_hd__mux2_1 _391_ (
    .A0(\u_fifo.fifomem.mem[15] [3]),
    .A1(_152_),
    .S(_166_),
    .X(_066_)
  );
  sky130_fd_sc_hd__mux2_1 _392_ (
    .A0(\u_fifo.fifomem.mem[15] [4]),
    .A1(_153_),
    .S(_166_),
    .X(_067_)
  );
  sky130_fd_sc_hd__mux2_1 _393_ (
    .A0(\u_fifo.fifomem.mem[15] [5]),
    .A1(_154_),
    .S(_166_),
    .X(_068_)
  );
  sky130_fd_sc_hd__mux2_1 _394_ (
    .A0(\u_fifo.fifomem.mem[15] [6]),
    .A1(_155_),
    .S(_166_),
    .X(_069_)
  );
  sky130_fd_sc_hd__mux2_1 _395_ (
    .A0(\u_fifo.fifomem.mem[15] [7]),
    .A1(_156_),
    .S(_166_),
    .X(_070_)
  );
  sky130_fd_sc_hd__nor3_1 _396_ (
    .A(\u_fifo.fifomem.waddr [0]),
    .B(_144_),
    .C(_164_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__mux2_1 _397_ (
    .A0(\u_fifo.fifomem.mem[14] [0]),
    .A1(_149_),
    .S(_167_),
    .X(_055_)
  );
  sky130_fd_sc_hd__mux2_1 _398_ (
    .A0(\u_fifo.fifomem.mem[14] [1]),
    .A1(_150_),
    .S(_167_),
    .X(_056_)
  );
  sky130_fd_sc_hd__mux2_1 _399_ (
    .A0(\u_fifo.fifomem.mem[14] [2]),
    .A1(_151_),
    .S(_167_),
    .X(_057_)
  );
  sky130_fd_sc_hd__mux2_1 _400_ (
    .A0(\u_fifo.fifomem.mem[14] [3]),
    .A1(_152_),
    .S(_167_),
    .X(_058_)
  );
  sky130_fd_sc_hd__mux2_1 _401_ (
    .A0(\u_fifo.fifomem.mem[14] [4]),
    .A1(_153_),
    .S(_167_),
    .X(_059_)
  );
  sky130_fd_sc_hd__mux2_1 _402_ (
    .A0(\u_fifo.fifomem.mem[14] [5]),
    .A1(_154_),
    .S(_167_),
    .X(_060_)
  );
  sky130_fd_sc_hd__mux2_1 _403_ (
    .A0(\u_fifo.fifomem.mem[14] [6]),
    .A1(_155_),
    .S(_167_),
    .X(_061_)
  );
  sky130_fd_sc_hd__mux2_1 _404_ (
    .A0(\u_fifo.fifomem.mem[14] [7]),
    .A1(_156_),
    .S(_167_),
    .X(_062_)
  );
  sky130_fd_sc_hd__nand4_1 _405_ (
    .A(\u_fifo.fifomem.waddr [2]),
    .B(\u_fifo.fifomem.waddr [3]),
    .C(_143_),
    .D(_160_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__mux2_1 _406_ (
    .A0(_149_),
    .A1(\u_fifo.fifomem.mem[12] [0]),
    .S(_168_),
    .X(_039_)
  );
  sky130_fd_sc_hd__mux2_1 _407_ (
    .A0(_150_),
    .A1(\u_fifo.fifomem.mem[12] [1]),
    .S(_168_),
    .X(_040_)
  );
  sky130_fd_sc_hd__mux2_1 _408_ (
    .A0(_151_),
    .A1(\u_fifo.fifomem.mem[12] [2]),
    .S(_168_),
    .X(_041_)
  );
  sky130_fd_sc_hd__mux2_1 _409_ (
    .A0(_152_),
    .A1(\u_fifo.fifomem.mem[12] [3]),
    .S(_168_),
    .X(_042_)
  );
  sky130_fd_sc_hd__mux2_1 _410_ (
    .A0(_153_),
    .A1(\u_fifo.fifomem.mem[12] [4]),
    .S(_168_),
    .X(_043_)
  );
  sky130_fd_sc_hd__mux2_1 _411_ (
    .A0(_154_),
    .A1(\u_fifo.fifomem.mem[12] [5]),
    .S(_168_),
    .X(_044_)
  );
  sky130_fd_sc_hd__mux2_1 _412_ (
    .A0(_155_),
    .A1(\u_fifo.fifomem.mem[12] [6]),
    .S(_168_),
    .X(_045_)
  );
  sky130_fd_sc_hd__mux2_1 _413_ (
    .A0(_156_),
    .A1(\u_fifo.fifomem.mem[12] [7]),
    .S(_168_),
    .X(_046_)
  );
  sky130_fd_sc_hd__and3b_1 _414_ (
    .A_N(\u_fifo.fifomem.waddr [3]),
    .B(_143_),
    .C(\u_fifo.fifomem.waddr [2]),
    .X(_169_)
  );
  sky130_fd_sc_hd__nand2_1 _415_ (
    .A(_145_),
    .B(_169_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__mux2_1 _416_ (
    .A0(_149_),
    .A1(\u_fifo.fifomem.mem[6] [0]),
    .S(_170_),
    .X(_111_)
  );
  sky130_fd_sc_hd__mux2_1 _417_ (
    .A0(_150_),
    .A1(\u_fifo.fifomem.mem[6] [1]),
    .S(_170_),
    .X(_112_)
  );
  sky130_fd_sc_hd__mux2_1 _418_ (
    .A0(_151_),
    .A1(\u_fifo.fifomem.mem[6] [2]),
    .S(_170_),
    .X(_113_)
  );
  sky130_fd_sc_hd__mux2_1 _419_ (
    .A0(_152_),
    .A1(\u_fifo.fifomem.mem[6] [3]),
    .S(_170_),
    .X(_114_)
  );
  sky130_fd_sc_hd__mux2_1 _420_ (
    .A0(_153_),
    .A1(\u_fifo.fifomem.mem[6] [4]),
    .S(_170_),
    .X(_115_)
  );
  sky130_fd_sc_hd__mux2_1 _421_ (
    .A0(_154_),
    .A1(\u_fifo.fifomem.mem[6] [5]),
    .S(_170_),
    .X(_116_)
  );
  sky130_fd_sc_hd__mux2_1 _422_ (
    .A0(_155_),
    .A1(\u_fifo.fifomem.mem[6] [6]),
    .S(_170_),
    .X(_117_)
  );
  sky130_fd_sc_hd__mux2_1 _423_ (
    .A0(_156_),
    .A1(\u_fifo.fifomem.mem[6] [7]),
    .S(_170_),
    .X(_118_)
  );
  sky130_fd_sc_hd__mux4_2 _424_ (
    .A0(\u_fifo.fifomem.mem[10] [0]),
    .A1(\u_fifo.fifomem.mem[11] [0]),
    .A2(\u_fifo.fifomem.mem[14] [0]),
    .A3(\u_fifo.fifomem.mem[15] [0]),
    .S0(\u_fifo.fifomem.raddr [0]),
    .S1(\u_fifo.fifomem.raddr [2]),
    .X(_171_)
  );
  sky130_fd_sc_hd__mux4_2 _425_ (
    .A0(\u_fifo.fifomem.mem[8] [0]),
    .A1(\u_fifo.fifomem.mem[12] [0]),
    .A2(\u_fifo.fifomem.mem[9] [0]),
    .A3(\u_fifo.fifomem.mem[13] [0]),
    .S0(\u_fifo.fifomem.raddr [2]),
    .S1(\u_fifo.fifomem.raddr [0]),
    .X(_172_)
  );
  sky130_fd_sc_hd__mux4_2 _426_ (
    .A0(\u_fifo.fifomem.mem[2] [0]),
    .A1(\u_fifo.fifomem.mem[3] [0]),
    .A2(\u_fifo.fifomem.mem[6] [0]),
    .A3(\u_fifo.fifomem.mem[7] [0]),
    .S0(\u_fifo.fifomem.raddr [0]),
    .S1(\u_fifo.fifomem.raddr [2]),
    .X(_173_)
  );
  sky130_fd_sc_hd__mux4_2 _427_ (
    .A0(\u_fifo.fifomem.mem[0] [0]),
    .A1(\u_fifo.fifomem.mem[4] [0]),
    .A2(\u_fifo.fifomem.mem[1] [0]),
    .A3(\u_fifo.fifomem.mem[5] [0]),
    .S0(\u_fifo.fifomem.raddr [2]),
    .S1(\u_fifo.fifomem.raddr [0]),
    .X(_174_)
  );
  sky130_fd_sc_hd__mux4_2 _428_ (
    .A0(_174_),
    .A1(_173_),
    .A2(_172_),
    .A3(_171_),
    .S0(\u_fifo.fifomem.raddr [1]),
    .S1(\u_fifo.fifomem.raddr [3]),
    .X(rdata_o[0])
  );
  sky130_fd_sc_hd__mux4_2 _429_ (
    .A0(\u_fifo.fifomem.mem[2] [1]),
    .A1(\u_fifo.fifomem.mem[3] [1]),
    .A2(\u_fifo.fifomem.mem[6] [1]),
    .A3(\u_fifo.fifomem.mem[7] [1]),
    .S0(\u_fifo.fifomem.raddr [0]),
    .S1(\u_fifo.fifomem.raddr [2]),
    .X(_175_)
  );
  sky130_fd_sc_hd__mux4_2 _430_ (
    .A0(\u_fifo.fifomem.mem[0] [1]),
    .A1(\u_fifo.fifomem.mem[4] [1]),
    .A2(\u_fifo.fifomem.mem[1] [1]),
    .A3(\u_fifo.fifomem.mem[5] [1]),
    .S0(\u_fifo.fifomem.raddr [2]),
    .S1(\u_fifo.fifomem.raddr [0]),
    .X(_176_)
  );
  sky130_fd_sc_hd__mux4_2 _431_ (
    .A0(\u_fifo.fifomem.mem[10] [1]),
    .A1(\u_fifo.fifomem.mem[11] [1]),
    .A2(\u_fifo.fifomem.mem[14] [1]),
    .A3(\u_fifo.fifomem.mem[15] [1]),
    .S0(\u_fifo.fifomem.raddr [0]),
    .S1(\u_fifo.fifomem.raddr [2]),
    .X(_177_)
  );
  sky130_fd_sc_hd__mux4_2 _432_ (
    .A0(\u_fifo.fifomem.mem[8] [1]),
    .A1(\u_fifo.fifomem.mem[12] [1]),
    .A2(\u_fifo.fifomem.mem[9] [1]),
    .A3(\u_fifo.fifomem.mem[13] [1]),
    .S0(\u_fifo.fifomem.raddr [2]),
    .S1(\u_fifo.fifomem.raddr [0]),
    .X(_178_)
  );
  sky130_fd_sc_hd__mux4_2 _433_ (
    .A0(_176_),
    .A1(_178_),
    .A2(_175_),
    .A3(_177_),
    .S0(\u_fifo.fifomem.raddr [3]),
    .S1(\u_fifo.fifomem.raddr [1]),
    .X(rdata_o[1])
  );
  sky130_fd_sc_hd__mux4_2 _434_ (
    .A0(\u_fifo.fifomem.mem[2] [2]),
    .A1(\u_fifo.fifomem.mem[3] [2]),
    .A2(\u_fifo.fifomem.mem[6] [2]),
    .A3(\u_fifo.fifomem.mem[7] [2]),
    .S0(\u_fifo.fifomem.raddr [0]),
    .S1(\u_fifo.fifomem.raddr [2]),
    .X(_179_)
  );
  sky130_fd_sc_hd__mux4_2 _435_ (
    .A0(\u_fifo.fifomem.mem[0] [2]),
    .A1(\u_fifo.fifomem.mem[4] [2]),
    .A2(\u_fifo.fifomem.mem[1] [2]),
    .A3(\u_fifo.fifomem.mem[5] [2]),
    .S0(\u_fifo.fifomem.raddr [2]),
    .S1(\u_fifo.fifomem.raddr [0]),
    .X(_180_)
  );
  sky130_fd_sc_hd__mux2i_1 _436_ (
    .A0(_180_),
    .A1(_179_),
    .S(\u_fifo.fifomem.raddr [1]),
    .Y(_181_)
  );
  sky130_fd_sc_hd__mux4_2 _437_ (
    .A0(\u_fifo.fifomem.mem[9] [2]),
    .A1(\u_fifo.fifomem.mem[11] [2]),
    .A2(\u_fifo.fifomem.mem[13] [2]),
    .A3(\u_fifo.fifomem.mem[15] [2]),
    .S0(\u_fifo.fifomem.raddr [1]),
    .S1(\u_fifo.fifomem.raddr [2]),
    .X(_182_)
  );
  sky130_fd_sc_hd__nand2b_1 _438_ (
    .A_N(_182_),
    .B(\u_fifo.fifomem.raddr [0]),
    .Y(_183_)
  );
  sky130_fd_sc_hd__mux4_2 _439_ (
    .A0(\u_fifo.fifomem.mem[8] [2]),
    .A1(\u_fifo.fifomem.mem[12] [2]),
    .A2(\u_fifo.fifomem.mem[10] [2]),
    .A3(\u_fifo.fifomem.mem[14] [2]),
    .S0(\u_fifo.fifomem.raddr [2]),
    .S1(\u_fifo.fifomem.raddr [1]),
    .X(_184_)
  );
  sky130_fd_sc_hd__o211ai_1 _440_ (
    .A1(\u_fifo.fifomem.raddr [0]),
    .A2(_184_),
    .B1(_183_),
    .C1(\u_fifo.fifomem.raddr [3]),
    .Y(_185_)
  );
  sky130_fd_sc_hd__o21ai_0 _441_ (
    .A1(\u_fifo.fifomem.raddr [3]),
    .A2(_181_),
    .B1(_185_),
    .Y(rdata_o[2])
  );
  sky130_fd_sc_hd__mux4_2 _442_ (
    .A0(\u_fifo.fifomem.mem[10] [3]),
    .A1(\u_fifo.fifomem.mem[11] [3]),
    .A2(\u_fifo.fifomem.mem[14] [3]),
    .A3(\u_fifo.fifomem.mem[15] [3]),
    .S0(\u_fifo.fifomem.raddr [0]),
    .S1(\u_fifo.fifomem.raddr [2]),
    .X(_186_)
  );
  sky130_fd_sc_hd__mux4_2 _443_ (
    .A0(\u_fifo.fifomem.mem[8] [3]),
    .A1(\u_fifo.fifomem.mem[12] [3]),
    .A2(\u_fifo.fifomem.mem[9] [3]),
    .A3(\u_fifo.fifomem.mem[13] [3]),
    .S0(\u_fifo.fifomem.raddr [2]),
    .S1(\u_fifo.fifomem.raddr [0]),
    .X(_187_)
  );
  sky130_fd_sc_hd__mux4_2 _444_ (
    .A0(\u_fifo.fifomem.mem[2] [3]),
    .A1(\u_fifo.fifomem.mem[3] [3]),
    .A2(\u_fifo.fifomem.mem[6] [3]),
    .A3(\u_fifo.fifomem.mem[7] [3]),
    .S0(\u_fifo.fifomem.raddr [0]),
    .S1(\u_fifo.fifomem.raddr [2]),
    .X(_188_)
  );
  sky130_fd_sc_hd__mux4_2 _445_ (
    .A0(\u_fifo.fifomem.mem[0] [3]),
    .A1(\u_fifo.fifomem.mem[4] [3]),
    .A2(\u_fifo.fifomem.mem[1] [3]),
    .A3(\u_fifo.fifomem.mem[5] [3]),
    .S0(\u_fifo.fifomem.raddr [2]),
    .S1(\u_fifo.fifomem.raddr [0]),
    .X(_189_)
  );
  sky130_fd_sc_hd__mux4_2 _446_ (
    .A0(_189_),
    .A1(_188_),
    .A2(_187_),
    .A3(_186_),
    .S0(\u_fifo.fifomem.raddr [1]),
    .S1(\u_fifo.fifomem.raddr [3]),
    .X(rdata_o[3])
  );
  sky130_fd_sc_hd__mux4_2 _447_ (
    .A0(\u_fifo.fifomem.mem[10] [4]),
    .A1(\u_fifo.fifomem.mem[11] [4]),
    .A2(\u_fifo.fifomem.mem[14] [4]),
    .A3(\u_fifo.fifomem.mem[15] [4]),
    .S0(\u_fifo.fifomem.raddr [0]),
    .S1(\u_fifo.fifomem.raddr [2]),
    .X(_190_)
  );
  sky130_fd_sc_hd__mux4_2 _448_ (
    .A0(\u_fifo.fifomem.mem[2] [4]),
    .A1(\u_fifo.fifomem.mem[3] [4]),
    .A2(\u_fifo.fifomem.mem[6] [4]),
    .A3(\u_fifo.fifomem.mem[7] [4]),
    .S0(\u_fifo.fifomem.raddr [0]),
    .S1(\u_fifo.fifomem.raddr [2]),
    .X(_191_)
  );
  sky130_fd_sc_hd__mux4_2 _449_ (
    .A0(\u_fifo.fifomem.mem[8] [4]),
    .A1(\u_fifo.fifomem.mem[12] [4]),
    .A2(\u_fifo.fifomem.mem[9] [4]),
    .A3(\u_fifo.fifomem.mem[13] [4]),
    .S0(\u_fifo.fifomem.raddr [2]),
    .S1(\u_fifo.fifomem.raddr [0]),
    .X(_192_)
  );
  sky130_fd_sc_hd__mux4_2 _450_ (
    .A0(\u_fifo.fifomem.mem[0] [4]),
    .A1(\u_fifo.fifomem.mem[4] [4]),
    .A2(\u_fifo.fifomem.mem[1] [4]),
    .A3(\u_fifo.fifomem.mem[5] [4]),
    .S0(\u_fifo.fifomem.raddr [2]),
    .S1(\u_fifo.fifomem.raddr [0]),
    .X(_193_)
  );
  sky130_fd_sc_hd__mux4_2 _451_ (
    .A0(_193_),
    .A1(_192_),
    .A2(_191_),
    .A3(_190_),
    .S0(\u_fifo.fifomem.raddr [3]),
    .S1(\u_fifo.fifomem.raddr [1]),
    .X(rdata_o[4])
  );
  sky130_fd_sc_hd__mux4_2 _452_ (
    .A0(\u_fifo.fifomem.mem[10] [5]),
    .A1(\u_fifo.fifomem.mem[11] [5]),
    .A2(\u_fifo.fifomem.mem[14] [5]),
    .A3(\u_fifo.fifomem.mem[15] [5]),
    .S0(\u_fifo.fifomem.raddr [0]),
    .S1(\u_fifo.fifomem.raddr [2]),
    .X(_194_)
  );
  sky130_fd_sc_hd__mux4_2 _453_ (
    .A0(\u_fifo.fifomem.mem[8] [5]),
    .A1(\u_fifo.fifomem.mem[12] [5]),
    .A2(\u_fifo.fifomem.mem[9] [5]),
    .A3(\u_fifo.fifomem.mem[13] [5]),
    .S0(\u_fifo.fifomem.raddr [2]),
    .S1(\u_fifo.fifomem.raddr [0]),
    .X(_195_)
  );
  sky130_fd_sc_hd__mux4_2 _454_ (
    .A0(\u_fifo.fifomem.mem[2] [5]),
    .A1(\u_fifo.fifomem.mem[3] [5]),
    .A2(\u_fifo.fifomem.mem[6] [5]),
    .A3(\u_fifo.fifomem.mem[7] [5]),
    .S0(\u_fifo.fifomem.raddr [0]),
    .S1(\u_fifo.fifomem.raddr [2]),
    .X(_196_)
  );
  sky130_fd_sc_hd__mux4_2 _455_ (
    .A0(\u_fifo.fifomem.mem[0] [5]),
    .A1(\u_fifo.fifomem.mem[4] [5]),
    .A2(\u_fifo.fifomem.mem[1] [5]),
    .A3(\u_fifo.fifomem.mem[5] [5]),
    .S0(\u_fifo.fifomem.raddr [2]),
    .S1(\u_fifo.fifomem.raddr [0]),
    .X(_197_)
  );
  sky130_fd_sc_hd__mux4_2 _456_ (
    .A0(_197_),
    .A1(_196_),
    .A2(_195_),
    .A3(_194_),
    .S0(\u_fifo.fifomem.raddr [1]),
    .S1(\u_fifo.fifomem.raddr [3]),
    .X(rdata_o[5])
  );
  sky130_fd_sc_hd__mux4_2 _457_ (
    .A0(\u_fifo.fifomem.mem[2] [6]),
    .A1(\u_fifo.fifomem.mem[3] [6]),
    .A2(\u_fifo.fifomem.mem[6] [6]),
    .A3(\u_fifo.fifomem.mem[7] [6]),
    .S0(\u_fifo.fifomem.raddr [0]),
    .S1(\u_fifo.fifomem.raddr [2]),
    .X(_198_)
  );
  sky130_fd_sc_hd__mux4_2 _458_ (
    .A0(\u_fifo.fifomem.mem[0] [6]),
    .A1(\u_fifo.fifomem.mem[4] [6]),
    .A2(\u_fifo.fifomem.mem[1] [6]),
    .A3(\u_fifo.fifomem.mem[5] [6]),
    .S0(\u_fifo.fifomem.raddr [2]),
    .S1(\u_fifo.fifomem.raddr [0]),
    .X(_199_)
  );
  sky130_fd_sc_hd__mux4_2 _459_ (
    .A0(\u_fifo.fifomem.mem[10] [6]),
    .A1(\u_fifo.fifomem.mem[11] [6]),
    .A2(\u_fifo.fifomem.mem[14] [6]),
    .A3(\u_fifo.fifomem.mem[15] [6]),
    .S0(\u_fifo.fifomem.raddr [0]),
    .S1(\u_fifo.fifomem.raddr [2]),
    .X(_200_)
  );
  sky130_fd_sc_hd__mux4_2 _460_ (
    .A0(\u_fifo.fifomem.mem[8] [6]),
    .A1(\u_fifo.fifomem.mem[12] [6]),
    .A2(\u_fifo.fifomem.mem[9] [6]),
    .A3(\u_fifo.fifomem.mem[13] [6]),
    .S0(\u_fifo.fifomem.raddr [2]),
    .S1(\u_fifo.fifomem.raddr [0]),
    .X(_201_)
  );
  sky130_fd_sc_hd__mux4_2 _461_ (
    .A0(_199_),
    .A1(_201_),
    .A2(_198_),
    .A3(_200_),
    .S0(\u_fifo.fifomem.raddr [3]),
    .S1(\u_fifo.fifomem.raddr [1]),
    .X(rdata_o[6])
  );
  sky130_fd_sc_hd__mux4_2 _462_ (
    .A0(\u_fifo.fifomem.mem[2] [7]),
    .A1(\u_fifo.fifomem.mem[3] [7]),
    .A2(\u_fifo.fifomem.mem[6] [7]),
    .A3(\u_fifo.fifomem.mem[7] [7]),
    .S0(\u_fifo.fifomem.raddr [0]),
    .S1(\u_fifo.fifomem.raddr [2]),
    .X(_202_)
  );
  sky130_fd_sc_hd__mux4_2 _463_ (
    .A0(\u_fifo.fifomem.mem[0] [7]),
    .A1(\u_fifo.fifomem.mem[4] [7]),
    .A2(\u_fifo.fifomem.mem[1] [7]),
    .A3(\u_fifo.fifomem.mem[5] [7]),
    .S0(\u_fifo.fifomem.raddr [2]),
    .S1(\u_fifo.fifomem.raddr [0]),
    .X(_203_)
  );
  sky130_fd_sc_hd__mux4_2 _464_ (
    .A0(\u_fifo.fifomem.mem[10] [7]),
    .A1(\u_fifo.fifomem.mem[11] [7]),
    .A2(\u_fifo.fifomem.mem[14] [7]),
    .A3(\u_fifo.fifomem.mem[15] [7]),
    .S0(\u_fifo.fifomem.raddr [0]),
    .S1(\u_fifo.fifomem.raddr [2]),
    .X(_204_)
  );
  sky130_fd_sc_hd__mux4_2 _465_ (
    .A0(\u_fifo.fifomem.mem[8] [7]),
    .A1(\u_fifo.fifomem.mem[12] [7]),
    .A2(\u_fifo.fifomem.mem[9] [7]),
    .A3(\u_fifo.fifomem.mem[13] [7]),
    .S0(\u_fifo.fifomem.raddr [2]),
    .S1(\u_fifo.fifomem.raddr [0]),
    .X(_205_)
  );
  sky130_fd_sc_hd__mux4_2 _466_ (
    .A0(_203_),
    .A1(_205_),
    .A2(_202_),
    .A3(_204_),
    .S0(\u_fifo.fifomem.raddr [3]),
    .S1(\u_fifo.fifomem.raddr [1]),
    .X(rdata_o[7])
  );
  sky130_fd_sc_hd__o21ai_0 _467_ (
    .A1(\u_fifo.fifomem.waddr [2]),
    .A2(\u_fifo.fifomem.waddr [3]),
    .B1(_143_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__nand2_1 _468_ (
    .A(_158_),
    .B(_206_),
    .Y(_207_)
  );
  sky130_fd_sc_hd__mux2_1 _469_ (
    .A0(_149_),
    .A1(\u_fifo.fifomem.mem[1] [0]),
    .S(_207_),
    .X(_071_)
  );
  sky130_fd_sc_hd__mux2_1 _470_ (
    .A0(_150_),
    .A1(\u_fifo.fifomem.mem[1] [1]),
    .S(_207_),
    .X(_072_)
  );
  sky130_fd_sc_hd__mux2_1 _471_ (
    .A0(_151_),
    .A1(\u_fifo.fifomem.mem[1] [2]),
    .S(_207_),
    .X(_073_)
  );
  sky130_fd_sc_hd__mux2_1 _472_ (
    .A0(_152_),
    .A1(\u_fifo.fifomem.mem[1] [3]),
    .S(_207_),
    .X(_074_)
  );
  sky130_fd_sc_hd__mux2_1 _473_ (
    .A0(_153_),
    .A1(\u_fifo.fifomem.mem[1] [4]),
    .S(_207_),
    .X(_075_)
  );
  sky130_fd_sc_hd__mux2_1 _474_ (
    .A0(_154_),
    .A1(\u_fifo.fifomem.mem[1] [5]),
    .S(_207_),
    .X(_076_)
  );
  sky130_fd_sc_hd__mux2_1 _475_ (
    .A0(_155_),
    .A1(\u_fifo.fifomem.mem[1] [6]),
    .S(_207_),
    .X(_077_)
  );
  sky130_fd_sc_hd__mux2_1 _476_ (
    .A0(_156_),
    .A1(\u_fifo.fifomem.mem[1] [7]),
    .S(_207_),
    .X(_078_)
  );
  sky130_fd_sc_hd__o41ai_1 _477_ (
    .A1(\u_fifo.fifomem.waddr [0]),
    .A2(\u_fifo.fifomem.waddr [1]),
    .A3(\u_fifo.fifomem.waddr [2]),
    .A4(\u_fifo.fifomem.waddr [3]),
    .B1(_143_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__nand2_1 _478_ (
    .A(_143_),
    .B(_208_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__a22o_1 _479_ (
    .A1(_149_),
    .A2(_208_),
    .B1(_209_),
    .B2(\u_fifo.fifomem.mem[0] [0]),
    .X(_015_)
  );
  sky130_fd_sc_hd__mux2_1 _480_ (
    .A0(\u_fifo.fifomem.wdata [1]),
    .A1(\u_fifo.fifomem.mem[0] [1]),
    .S(_209_),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _481_ (
    .A0(\u_fifo.fifomem.wdata [2]),
    .A1(\u_fifo.fifomem.mem[0] [2]),
    .S(_209_),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _482_ (
    .A0(\u_fifo.fifomem.wdata [3]),
    .A1(\u_fifo.fifomem.mem[0] [3]),
    .S(_209_),
    .X(_018_)
  );
  sky130_fd_sc_hd__mux2_1 _483_ (
    .A0(\u_fifo.fifomem.wdata [4]),
    .A1(\u_fifo.fifomem.mem[0] [4]),
    .S(_209_),
    .X(_019_)
  );
  sky130_fd_sc_hd__mux2_1 _484_ (
    .A0(\u_fifo.fifomem.wdata [5]),
    .A1(\u_fifo.fifomem.mem[0] [5]),
    .S(_209_),
    .X(_020_)
  );
  sky130_fd_sc_hd__mux2_1 _485_ (
    .A0(\u_fifo.fifomem.wdata [6]),
    .A1(\u_fifo.fifomem.mem[0] [6]),
    .S(_209_),
    .X(_021_)
  );
  sky130_fd_sc_hd__a22o_1 _486_ (
    .A1(_156_),
    .A2(_208_),
    .B1(_209_),
    .B2(\u_fifo.fifomem.mem[0] [7]),
    .X(_022_)
  );
  sky130_fd_sc_hd__nor2b_1 _487_ (
    .A(_162_),
    .B_N(_169_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__mux2_1 _488_ (
    .A0(\u_fifo.fifomem.mem[7] [0]),
    .A1(_149_),
    .S(_210_),
    .X(_119_)
  );
  sky130_fd_sc_hd__mux2_1 _489_ (
    .A0(\u_fifo.fifomem.mem[7] [1]),
    .A1(_150_),
    .S(_210_),
    .X(_120_)
  );
  sky130_fd_sc_hd__mux2_1 _490_ (
    .A0(\u_fifo.fifomem.mem[7] [2]),
    .A1(_151_),
    .S(_210_),
    .X(_121_)
  );
  sky130_fd_sc_hd__mux2_1 _491_ (
    .A0(\u_fifo.fifomem.mem[7] [3]),
    .A1(_152_),
    .S(_210_),
    .X(_122_)
  );
  sky130_fd_sc_hd__mux2_1 _492_ (
    .A0(\u_fifo.fifomem.mem[7] [4]),
    .A1(_153_),
    .S(_210_),
    .X(_123_)
  );
  sky130_fd_sc_hd__mux2_1 _493_ (
    .A0(\u_fifo.fifomem.mem[7] [5]),
    .A1(_154_),
    .S(_210_),
    .X(_124_)
  );
  sky130_fd_sc_hd__mux2_1 _494_ (
    .A0(\u_fifo.fifomem.mem[7] [6]),
    .A1(_155_),
    .S(_210_),
    .X(_125_)
  );
  sky130_fd_sc_hd__mux2_1 _495_ (
    .A0(\u_fifo.fifomem.mem[7] [7]),
    .A1(_156_),
    .S(_210_),
    .X(_126_)
  );
  sky130_fd_sc_hd__nand2_1 _496_ (
    .A(_145_),
    .B(_206_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__mux2_1 _497_ (
    .A0(_149_),
    .A1(\u_fifo.fifomem.mem[2] [0]),
    .S(_211_),
    .X(_079_)
  );
  sky130_fd_sc_hd__mux2_1 _498_ (
    .A0(_150_),
    .A1(\u_fifo.fifomem.mem[2] [1]),
    .S(_211_),
    .X(_080_)
  );
  sky130_fd_sc_hd__mux2_1 _499_ (
    .A0(_151_),
    .A1(\u_fifo.fifomem.mem[2] [2]),
    .S(_211_),
    .X(_081_)
  );
  sky130_fd_sc_hd__mux2_1 _500_ (
    .A0(_152_),
    .A1(\u_fifo.fifomem.mem[2] [3]),
    .S(_211_),
    .X(_082_)
  );
  sky130_fd_sc_hd__mux2_1 _501_ (
    .A0(_153_),
    .A1(\u_fifo.fifomem.mem[2] [4]),
    .S(_211_),
    .X(_083_)
  );
  sky130_fd_sc_hd__mux2_1 _502_ (
    .A0(_154_),
    .A1(\u_fifo.fifomem.mem[2] [5]),
    .S(_211_),
    .X(_084_)
  );
  sky130_fd_sc_hd__mux2_1 _503_ (
    .A0(_155_),
    .A1(\u_fifo.fifomem.mem[2] [6]),
    .S(_211_),
    .X(_085_)
  );
  sky130_fd_sc_hd__mux2_1 _504_ (
    .A0(_156_),
    .A1(\u_fifo.fifomem.mem[2] [7]),
    .S(_211_),
    .X(_086_)
  );
  sky130_fd_sc_hd__nand2_1 _505_ (
    .A(_158_),
    .B(_169_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__mux2_1 _506_ (
    .A0(_149_),
    .A1(\u_fifo.fifomem.mem[5] [0]),
    .S(_212_),
    .X(_103_)
  );
  sky130_fd_sc_hd__mux2_1 _507_ (
    .A0(_150_),
    .A1(\u_fifo.fifomem.mem[5] [1]),
    .S(_212_),
    .X(_104_)
  );
  sky130_fd_sc_hd__mux2_1 _508_ (
    .A0(_151_),
    .A1(\u_fifo.fifomem.mem[5] [2]),
    .S(_212_),
    .X(_105_)
  );
  sky130_fd_sc_hd__mux2_1 _509_ (
    .A0(_152_),
    .A1(\u_fifo.fifomem.mem[5] [3]),
    .S(_212_),
    .X(_106_)
  );
  sky130_fd_sc_hd__mux2_1 _510_ (
    .A0(_153_),
    .A1(\u_fifo.fifomem.mem[5] [4]),
    .S(_212_),
    .X(_107_)
  );
  sky130_fd_sc_hd__mux2_1 _511_ (
    .A0(_154_),
    .A1(\u_fifo.fifomem.mem[5] [5]),
    .S(_212_),
    .X(_108_)
  );
  sky130_fd_sc_hd__mux2_1 _512_ (
    .A0(_155_),
    .A1(\u_fifo.fifomem.mem[5] [6]),
    .S(_212_),
    .X(_109_)
  );
  sky130_fd_sc_hd__mux2_1 _513_ (
    .A0(_156_),
    .A1(\u_fifo.fifomem.mem[5] [7]),
    .S(_212_),
    .X(_110_)
  );
  sky130_fd_sc_hd__nand2b_1 _514_ (
    .A_N(_162_),
    .B(_206_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__mux2_1 _515_ (
    .A0(_149_),
    .A1(\u_fifo.fifomem.mem[3] [0]),
    .S(_213_),
    .X(_087_)
  );
  sky130_fd_sc_hd__mux2_1 _516_ (
    .A0(_150_),
    .A1(\u_fifo.fifomem.mem[3] [1]),
    .S(_213_),
    .X(_088_)
  );
  sky130_fd_sc_hd__mux2_1 _517_ (
    .A0(_151_),
    .A1(\u_fifo.fifomem.mem[3] [2]),
    .S(_213_),
    .X(_089_)
  );
  sky130_fd_sc_hd__mux2_1 _518_ (
    .A0(_152_),
    .A1(\u_fifo.fifomem.mem[3] [3]),
    .S(_213_),
    .X(_090_)
  );
  sky130_fd_sc_hd__mux2_1 _519_ (
    .A0(_153_),
    .A1(\u_fifo.fifomem.mem[3] [4]),
    .S(_213_),
    .X(_091_)
  );
  sky130_fd_sc_hd__mux2_1 _520_ (
    .A0(_154_),
    .A1(\u_fifo.fifomem.mem[3] [5]),
    .S(_213_),
    .X(_092_)
  );
  sky130_fd_sc_hd__mux2_1 _521_ (
    .A0(_155_),
    .A1(\u_fifo.fifomem.mem[3] [6]),
    .S(_213_),
    .X(_093_)
  );
  sky130_fd_sc_hd__mux2_1 _522_ (
    .A0(_156_),
    .A1(\u_fifo.fifomem.mem[3] [7]),
    .S(_213_),
    .X(_094_)
  );
  sky130_fd_sc_hd__nand2_1 _523_ (
    .A(_160_),
    .B(_169_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__mux2_1 _524_ (
    .A0(_149_),
    .A1(\u_fifo.fifomem.mem[4] [0]),
    .S(_214_),
    .X(_095_)
  );
  sky130_fd_sc_hd__mux2_1 _525_ (
    .A0(_150_),
    .A1(\u_fifo.fifomem.mem[4] [1]),
    .S(_214_),
    .X(_096_)
  );
  sky130_fd_sc_hd__mux2_1 _526_ (
    .A0(_151_),
    .A1(\u_fifo.fifomem.mem[4] [2]),
    .S(_214_),
    .X(_097_)
  );
  sky130_fd_sc_hd__mux2_1 _527_ (
    .A0(_152_),
    .A1(\u_fifo.fifomem.mem[4] [3]),
    .S(_214_),
    .X(_098_)
  );
  sky130_fd_sc_hd__mux2_1 _528_ (
    .A0(_153_),
    .A1(\u_fifo.fifomem.mem[4] [4]),
    .S(_214_),
    .X(_099_)
  );
  sky130_fd_sc_hd__mux2_1 _529_ (
    .A0(_154_),
    .A1(\u_fifo.fifomem.mem[4] [5]),
    .S(_214_),
    .X(_100_)
  );
  sky130_fd_sc_hd__mux2_1 _530_ (
    .A0(_155_),
    .A1(\u_fifo.fifomem.mem[4] [6]),
    .S(_214_),
    .X(_101_)
  );
  sky130_fd_sc_hd__mux2_1 _531_ (
    .A0(_156_),
    .A1(\u_fifo.fifomem.mem[4] [7]),
    .S(_214_),
    .X(_102_)
  );
  sky130_fd_sc_hd__dfxtp_1 _532_ (
    .CLK(wclk_raw),
    .D(_079_),
    .Q(\u_fifo.fifomem.mem[2] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _533_ (
    .CLK(wclk_raw),
    .D(_080_),
    .Q(\u_fifo.fifomem.mem[2] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _534_ (
    .CLK(wclk_raw),
    .D(_081_),
    .Q(\u_fifo.fifomem.mem[2] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _535_ (
    .CLK(wclk_raw),
    .D(_082_),
    .Q(\u_fifo.fifomem.mem[2] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _536_ (
    .CLK(wclk_raw),
    .D(_083_),
    .Q(\u_fifo.fifomem.mem[2] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _537_ (
    .CLK(wclk_raw),
    .D(_084_),
    .Q(\u_fifo.fifomem.mem[2] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _538_ (
    .CLK(wclk_raw),
    .D(_085_),
    .Q(\u_fifo.fifomem.mem[2] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _539_ (
    .CLK(wclk_raw),
    .D(_086_),
    .Q(\u_fifo.fifomem.mem[2] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _540_ (
    .CLK(wclk_raw),
    .D(_071_),
    .Q(\u_fifo.fifomem.mem[1] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _541_ (
    .CLK(wclk_raw),
    .D(_072_),
    .Q(\u_fifo.fifomem.mem[1] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _542_ (
    .CLK(wclk_raw),
    .D(_073_),
    .Q(\u_fifo.fifomem.mem[1] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _543_ (
    .CLK(wclk_raw),
    .D(_074_),
    .Q(\u_fifo.fifomem.mem[1] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _544_ (
    .CLK(wclk_raw),
    .D(_075_),
    .Q(\u_fifo.fifomem.mem[1] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _545_ (
    .CLK(wclk_raw),
    .D(_076_),
    .Q(\u_fifo.fifomem.mem[1] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _546_ (
    .CLK(wclk_raw),
    .D(_077_),
    .Q(\u_fifo.fifomem.mem[1] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _547_ (
    .CLK(wclk_raw),
    .D(_078_),
    .Q(\u_fifo.fifomem.mem[1] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _548_ (
    .CLK(wclk_raw),
    .D(_087_),
    .Q(\u_fifo.fifomem.mem[3] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _549_ (
    .CLK(wclk_raw),
    .D(_088_),
    .Q(\u_fifo.fifomem.mem[3] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _550_ (
    .CLK(wclk_raw),
    .D(_089_),
    .Q(\u_fifo.fifomem.mem[3] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _551_ (
    .CLK(wclk_raw),
    .D(_090_),
    .Q(\u_fifo.fifomem.mem[3] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _552_ (
    .CLK(wclk_raw),
    .D(_091_),
    .Q(\u_fifo.fifomem.mem[3] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _553_ (
    .CLK(wclk_raw),
    .D(_092_),
    .Q(\u_fifo.fifomem.mem[3] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _554_ (
    .CLK(wclk_raw),
    .D(_093_),
    .Q(\u_fifo.fifomem.mem[3] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _555_ (
    .CLK(wclk_raw),
    .D(_094_),
    .Q(\u_fifo.fifomem.mem[3] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _556_ (
    .CLK(wclk_raw),
    .D(_111_),
    .Q(\u_fifo.fifomem.mem[6] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _557_ (
    .CLK(wclk_raw),
    .D(_112_),
    .Q(\u_fifo.fifomem.mem[6] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _558_ (
    .CLK(wclk_raw),
    .D(_113_),
    .Q(\u_fifo.fifomem.mem[6] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _559_ (
    .CLK(wclk_raw),
    .D(_114_),
    .Q(\u_fifo.fifomem.mem[6] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _560_ (
    .CLK(wclk_raw),
    .D(_115_),
    .Q(\u_fifo.fifomem.mem[6] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _561_ (
    .CLK(wclk_raw),
    .D(_116_),
    .Q(\u_fifo.fifomem.mem[6] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _562_ (
    .CLK(wclk_raw),
    .D(_117_),
    .Q(\u_fifo.fifomem.mem[6] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _563_ (
    .CLK(wclk_raw),
    .D(_118_),
    .Q(\u_fifo.fifomem.mem[6] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _564_ (
    .CLK(wclk_raw),
    .D(_119_),
    .Q(\u_fifo.fifomem.mem[7] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _565_ (
    .CLK(wclk_raw),
    .D(_120_),
    .Q(\u_fifo.fifomem.mem[7] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _566_ (
    .CLK(wclk_raw),
    .D(_121_),
    .Q(\u_fifo.fifomem.mem[7] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _567_ (
    .CLK(wclk_raw),
    .D(_122_),
    .Q(\u_fifo.fifomem.mem[7] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _568_ (
    .CLK(wclk_raw),
    .D(_123_),
    .Q(\u_fifo.fifomem.mem[7] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _569_ (
    .CLK(wclk_raw),
    .D(_124_),
    .Q(\u_fifo.fifomem.mem[7] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _570_ (
    .CLK(wclk_raw),
    .D(_125_),
    .Q(\u_fifo.fifomem.mem[7] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _571_ (
    .CLK(wclk_raw),
    .D(_126_),
    .Q(\u_fifo.fifomem.mem[7] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _572_ (
    .CLK(wclk_raw),
    .D(_127_),
    .Q(\u_fifo.fifomem.mem[8] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _573_ (
    .CLK(wclk_raw),
    .D(_128_),
    .Q(\u_fifo.fifomem.mem[8] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _574_ (
    .CLK(wclk_raw),
    .D(_129_),
    .Q(\u_fifo.fifomem.mem[8] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _575_ (
    .CLK(wclk_raw),
    .D(_130_),
    .Q(\u_fifo.fifomem.mem[8] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _576_ (
    .CLK(wclk_raw),
    .D(_131_),
    .Q(\u_fifo.fifomem.mem[8] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _577_ (
    .CLK(wclk_raw),
    .D(_132_),
    .Q(\u_fifo.fifomem.mem[8] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _578_ (
    .CLK(wclk_raw),
    .D(_133_),
    .Q(\u_fifo.fifomem.mem[8] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _579_ (
    .CLK(wclk_raw),
    .D(_134_),
    .Q(\u_fifo.fifomem.mem[8] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _580_ (
    .CLK(wclk_raw),
    .D(_135_),
    .Q(\u_fifo.fifomem.mem[9] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _581_ (
    .CLK(wclk_raw),
    .D(_136_),
    .Q(\u_fifo.fifomem.mem[9] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _582_ (
    .CLK(wclk_raw),
    .D(_137_),
    .Q(\u_fifo.fifomem.mem[9] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _583_ (
    .CLK(wclk_raw),
    .D(_138_),
    .Q(\u_fifo.fifomem.mem[9] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _584_ (
    .CLK(wclk_raw),
    .D(_139_),
    .Q(\u_fifo.fifomem.mem[9] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _585_ (
    .CLK(wclk_raw),
    .D(_140_),
    .Q(\u_fifo.fifomem.mem[9] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _586_ (
    .CLK(wclk_raw),
    .D(_141_),
    .Q(\u_fifo.fifomem.mem[9] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _587_ (
    .CLK(wclk_raw),
    .D(_142_),
    .Q(\u_fifo.fifomem.mem[9] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _588_ (
    .CLK(wclk_raw),
    .D(_015_),
    .Q(\u_fifo.fifomem.mem[0] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _589_ (
    .CLK(wclk_raw),
    .D(_016_),
    .Q(\u_fifo.fifomem.mem[0] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _590_ (
    .CLK(wclk_raw),
    .D(_017_),
    .Q(\u_fifo.fifomem.mem[0] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _591_ (
    .CLK(wclk_raw),
    .D(_018_),
    .Q(\u_fifo.fifomem.mem[0] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _592_ (
    .CLK(wclk_raw),
    .D(_019_),
    .Q(\u_fifo.fifomem.mem[0] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _593_ (
    .CLK(wclk_raw),
    .D(_020_),
    .Q(\u_fifo.fifomem.mem[0] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _594_ (
    .CLK(wclk_raw),
    .D(_021_),
    .Q(\u_fifo.fifomem.mem[0] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _595_ (
    .CLK(wclk_raw),
    .D(_022_),
    .Q(\u_fifo.fifomem.mem[0] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _596_ (
    .CLK(wclk_raw),
    .D(_063_),
    .Q(\u_fifo.fifomem.mem[15] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _597_ (
    .CLK(wclk_raw),
    .D(_064_),
    .Q(\u_fifo.fifomem.mem[15] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _598_ (
    .CLK(wclk_raw),
    .D(_065_),
    .Q(\u_fifo.fifomem.mem[15] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _599_ (
    .CLK(wclk_raw),
    .D(_066_),
    .Q(\u_fifo.fifomem.mem[15] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _600_ (
    .CLK(wclk_raw),
    .D(_067_),
    .Q(\u_fifo.fifomem.mem[15] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _601_ (
    .CLK(wclk_raw),
    .D(_068_),
    .Q(\u_fifo.fifomem.mem[15] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _602_ (
    .CLK(wclk_raw),
    .D(_069_),
    .Q(\u_fifo.fifomem.mem[15] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _603_ (
    .CLK(wclk_raw),
    .D(_070_),
    .Q(\u_fifo.fifomem.mem[15] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _604_ (
    .CLK(wclk_raw),
    .D(_055_),
    .Q(\u_fifo.fifomem.mem[14] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _605_ (
    .CLK(wclk_raw),
    .D(_056_),
    .Q(\u_fifo.fifomem.mem[14] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _606_ (
    .CLK(wclk_raw),
    .D(_057_),
    .Q(\u_fifo.fifomem.mem[14] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _607_ (
    .CLK(wclk_raw),
    .D(_058_),
    .Q(\u_fifo.fifomem.mem[14] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _608_ (
    .CLK(wclk_raw),
    .D(_059_),
    .Q(\u_fifo.fifomem.mem[14] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _609_ (
    .CLK(wclk_raw),
    .D(_060_),
    .Q(\u_fifo.fifomem.mem[14] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _610_ (
    .CLK(wclk_raw),
    .D(_061_),
    .Q(\u_fifo.fifomem.mem[14] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _611_ (
    .CLK(wclk_raw),
    .D(_062_),
    .Q(\u_fifo.fifomem.mem[14] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _612_ (
    .CLK(wclk_raw),
    .D(_047_),
    .Q(\u_fifo.fifomem.mem[13] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _613_ (
    .CLK(wclk_raw),
    .D(_048_),
    .Q(\u_fifo.fifomem.mem[13] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _614_ (
    .CLK(wclk_raw),
    .D(_049_),
    .Q(\u_fifo.fifomem.mem[13] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _615_ (
    .CLK(wclk_raw),
    .D(_050_),
    .Q(\u_fifo.fifomem.mem[13] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _616_ (
    .CLK(wclk_raw),
    .D(_051_),
    .Q(\u_fifo.fifomem.mem[13] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _617_ (
    .CLK(wclk_raw),
    .D(_052_),
    .Q(\u_fifo.fifomem.mem[13] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _618_ (
    .CLK(wclk_raw),
    .D(_053_),
    .Q(\u_fifo.fifomem.mem[13] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _619_ (
    .CLK(wclk_raw),
    .D(_054_),
    .Q(\u_fifo.fifomem.mem[13] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _620_ (
    .CLK(wclk_raw),
    .D(_039_),
    .Q(\u_fifo.fifomem.mem[12] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _621_ (
    .CLK(wclk_raw),
    .D(_040_),
    .Q(\u_fifo.fifomem.mem[12] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _622_ (
    .CLK(wclk_raw),
    .D(_041_),
    .Q(\u_fifo.fifomem.mem[12] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _623_ (
    .CLK(wclk_raw),
    .D(_042_),
    .Q(\u_fifo.fifomem.mem[12] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _624_ (
    .CLK(wclk_raw),
    .D(_043_),
    .Q(\u_fifo.fifomem.mem[12] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _625_ (
    .CLK(wclk_raw),
    .D(_044_),
    .Q(\u_fifo.fifomem.mem[12] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _626_ (
    .CLK(wclk_raw),
    .D(_045_),
    .Q(\u_fifo.fifomem.mem[12] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _627_ (
    .CLK(wclk_raw),
    .D(_046_),
    .Q(\u_fifo.fifomem.mem[12] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _628_ (
    .CLK(wclk_raw),
    .D(_103_),
    .Q(\u_fifo.fifomem.mem[5] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _629_ (
    .CLK(wclk_raw),
    .D(_104_),
    .Q(\u_fifo.fifomem.mem[5] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _630_ (
    .CLK(wclk_raw),
    .D(_105_),
    .Q(\u_fifo.fifomem.mem[5] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _631_ (
    .CLK(wclk_raw),
    .D(_106_),
    .Q(\u_fifo.fifomem.mem[5] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _632_ (
    .CLK(wclk_raw),
    .D(_107_),
    .Q(\u_fifo.fifomem.mem[5] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _633_ (
    .CLK(wclk_raw),
    .D(_108_),
    .Q(\u_fifo.fifomem.mem[5] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _634_ (
    .CLK(wclk_raw),
    .D(_109_),
    .Q(\u_fifo.fifomem.mem[5] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _635_ (
    .CLK(wclk_raw),
    .D(_110_),
    .Q(\u_fifo.fifomem.mem[5] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _636_ (
    .CLK(wclk_raw),
    .D(_095_),
    .Q(\u_fifo.fifomem.mem[4] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _637_ (
    .CLK(wclk_raw),
    .D(_096_),
    .Q(\u_fifo.fifomem.mem[4] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _638_ (
    .CLK(wclk_raw),
    .D(_097_),
    .Q(\u_fifo.fifomem.mem[4] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _639_ (
    .CLK(wclk_raw),
    .D(_098_),
    .Q(\u_fifo.fifomem.mem[4] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _640_ (
    .CLK(wclk_raw),
    .D(_099_),
    .Q(\u_fifo.fifomem.mem[4] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _641_ (
    .CLK(wclk_raw),
    .D(_100_),
    .Q(\u_fifo.fifomem.mem[4] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _642_ (
    .CLK(wclk_raw),
    .D(_101_),
    .Q(\u_fifo.fifomem.mem[4] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _643_ (
    .CLK(wclk_raw),
    .D(_102_),
    .Q(\u_fifo.fifomem.mem[4] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _644_ (
    .CLK(wclk_raw),
    .D(_031_),
    .Q(\u_fifo.fifomem.mem[11] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _645_ (
    .CLK(wclk_raw),
    .D(_032_),
    .Q(\u_fifo.fifomem.mem[11] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _646_ (
    .CLK(wclk_raw),
    .D(_033_),
    .Q(\u_fifo.fifomem.mem[11] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _647_ (
    .CLK(wclk_raw),
    .D(_034_),
    .Q(\u_fifo.fifomem.mem[11] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _648_ (
    .CLK(wclk_raw),
    .D(_035_),
    .Q(\u_fifo.fifomem.mem[11] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _649_ (
    .CLK(wclk_raw),
    .D(_036_),
    .Q(\u_fifo.fifomem.mem[11] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _650_ (
    .CLK(wclk_raw),
    .D(_037_),
    .Q(\u_fifo.fifomem.mem[11] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _651_ (
    .CLK(wclk_raw),
    .D(_038_),
    .Q(\u_fifo.fifomem.mem[11] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _652_ (
    .CLK(wclk_raw),
    .D(_023_),
    .Q(\u_fifo.fifomem.mem[10] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _653_ (
    .CLK(wclk_raw),
    .D(_024_),
    .Q(\u_fifo.fifomem.mem[10] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _654_ (
    .CLK(wclk_raw),
    .D(_025_),
    .Q(\u_fifo.fifomem.mem[10] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _655_ (
    .CLK(wclk_raw),
    .D(_026_),
    .Q(\u_fifo.fifomem.mem[10] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _656_ (
    .CLK(wclk_raw),
    .D(_027_),
    .Q(\u_fifo.fifomem.mem[10] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _657_ (
    .CLK(wclk_raw),
    .D(_028_),
    .Q(\u_fifo.fifomem.mem[10] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _658_ (
    .CLK(wclk_raw),
    .D(_029_),
    .Q(\u_fifo.fifomem.mem[10] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _659_ (
    .CLK(wclk_raw),
    .D(_030_),
    .Q(\u_fifo.fifomem.mem[10] [7])
  );
  sky130_fd_sc_hd__nand2b_1 _660_ (
    .A_N(rempty_o),
    .B(rinc),
    .Y(_215_)
  );
  sky130_fd_sc_hd__nand3b_1 _661_ (
    .A_N(rempty_o),
    .B(\u_fifo.fifomem.raddr [0]),
    .C(rinc),
    .Y(_216_)
  );
  sky130_fd_sc_hd__and4b_1 _662_ (
    .A_N(rempty_o),
    .B(\u_fifo.fifomem.raddr [0]),
    .C(\u_fifo.fifomem.raddr [1]),
    .D(rinc),
    .X(_217_)
  );
  sky130_fd_sc_hd__a21o_1 _663_ (
    .A1(\u_fifo.fifomem.raddr [2]),
    .A2(_217_),
    .B1(\u_fifo.fifomem.raddr [3]),
    .X(_218_)
  );
  sky130_fd_sc_hd__xor2_1 _664_ (
    .A(\u_fifo.rptr [4]),
    .B(_218_),
    .X(\u_fifo.rptr_empty.rgraynext [3])
  );
  sky130_fd_sc_hd__xnor2_1 _665_ (
    .A(\u_fifo.rptr_empty.rq2_wptr [3]),
    .B(\u_fifo.rptr_empty.rgraynext [3]),
    .Y(_219_)
  );
  sky130_fd_sc_hd__xnor2_1 _666_ (
    .A(\u_fifo.fifomem.raddr [1]),
    .B(_216_),
    .Y(\u_fifo.rptr_empty.rbinnext [1])
  );
  sky130_fd_sc_hd__nor2_1 _667_ (
    .A(\u_fifo.fifomem.raddr [2]),
    .B(_217_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__xor2_1 _668_ (
    .A(\u_fifo.fifomem.raddr [2]),
    .B(_217_),
    .X(\u_fifo.rptr_empty.rbinnext [2])
  );
  sky130_fd_sc_hd__xor2_1 _669_ (
    .A(\u_fifo.rptr_empty.rbinnext [1]),
    .B(\u_fifo.rptr_empty.rbinnext [2]),
    .X(\u_fifo.rptr_empty.rgraynext [1])
  );
  sky130_fd_sc_hd__xnor2_1 _670_ (
    .A(\u_fifo.rptr_empty.rq2_wptr [1]),
    .B(\u_fifo.rptr_empty.rgraynext [1]),
    .Y(_221_)
  );
  sky130_fd_sc_hd__nand3_1 _671_ (
    .A(\u_fifo.fifomem.raddr [2]),
    .B(\u_fifo.fifomem.raddr [3]),
    .C(_217_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__xor2_1 _672_ (
    .A(\u_fifo.rptr [4]),
    .B(_222_),
    .X(_223_)
  );
  sky130_fd_sc_hd__clkinv_1 _673_ (
    .A(_223_),
    .Y(\u_fifo.rptr_empty.rbinnext [4])
  );
  sky130_fd_sc_hd__xnor2_1 _674_ (
    .A(\u_fifo.rptr_empty.rq2_wptr [4]),
    .B(_223_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__xnor2_1 _675_ (
    .A(\u_fifo.fifomem.raddr [0]),
    .B(_215_),
    .Y(\u_fifo.rptr_empty.rbinnext [0])
  );
  sky130_fd_sc_hd__xnor2_1 _676_ (
    .A(\u_fifo.rptr_empty.rq2_wptr [0]),
    .B(\u_fifo.rptr_empty.rbinnext [1]),
    .Y(_225_)
  );
  sky130_fd_sc_hd__xnor2_1 _677_ (
    .A(\u_fifo.rptr_empty.rbinnext [0]),
    .B(_225_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__xnor2_1 _678_ (
    .A(\u_fifo.fifomem.raddr [3]),
    .B(_220_),
    .Y(\u_fifo.rptr_empty.rgraynext [2])
  );
  sky130_fd_sc_hd__xnor2_1 _679_ (
    .A(\u_fifo.rptr_empty.rq2_wptr [2]),
    .B(\u_fifo.rptr_empty.rgraynext [2]),
    .Y(_227_)
  );
  sky130_fd_sc_hd__nand3_1 _680_ (
    .A(_219_),
    .B(_221_),
    .C(_227_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__nor3_1 _681_ (
    .A(_224_),
    .B(_226_),
    .C(_228_),
    .Y(\u_fifo.rptr_empty.rempty_val )
  );
  sky130_fd_sc_hd__a21o_1 _682_ (
    .A1(\u_fifo.fifomem.raddr [1]),
    .A2(\u_fifo.rptr_empty.rbinnext [0]),
    .B1(\u_fifo.rptr_empty.rbinnext [2]),
    .X(_229_)
  );
  sky130_fd_sc_hd__nand3_1 _683_ (
    .A(\u_fifo.fifomem.raddr [1]),
    .B(\u_fifo.fifomem.raddr [2]),
    .C(\u_fifo.rptr_empty.rbinnext [0]),
    .Y(_230_)
  );
  sky130_fd_sc_hd__and2_0 _684_ (
    .A(_218_),
    .B(_222_),
    .X(\u_fifo.rptr_empty.rbinnext [3])
  );
  sky130_fd_sc_hd__and4_1 _685_ (
    .A(\u_fifo.fifomem.raddr [1]),
    .B(\u_fifo.fifomem.raddr [2]),
    .C(\u_fifo.fifomem.raddr [3]),
    .D(\u_fifo.rptr_empty.rbinnext [0]),
    .X(_231_)
  );
  sky130_fd_sc_hd__a32oi_1 _686_ (
    .A1(\u_fifo.fifomem.raddr [1]),
    .A2(\u_fifo.fifomem.raddr [2]),
    .A3(\u_fifo.rptr_empty.rbinnext [0]),
    .B1(_222_),
    .B2(_218_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__a211oi_1 _687_ (
    .A1(_229_),
    .A2(_230_),
    .B1(_231_),
    .C1(_232_),
    .Y(_233_)
  );
  sky130_fd_sc_hd__and2_0 _688_ (
    .A(_229_),
    .B(_232_),
    .X(_234_)
  );
  sky130_fd_sc_hd__o21ai_0 _689_ (
    .A1(_233_),
    .A2(_234_),
    .B1(\u_fifo.rptr_empty.rq2_wptr [2]),
    .Y(_235_)
  );
  sky130_fd_sc_hd__or3_1 _690_ (
    .A(\u_fifo.rptr_empty.rq2_wptr [2]),
    .B(_233_),
    .C(_234_),
    .X(_236_)
  );
  sky130_fd_sc_hd__xnor2_1 _691_ (
    .A(_223_),
    .B(_232_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__xnor2_1 _692_ (
    .A(\u_fifo.rptr_empty.rq2_wptr [3]),
    .B(_237_),
    .Y(_238_)
  );
  sky130_fd_sc_hd__nor2_1 _693_ (
    .A(\u_fifo.rptr_empty.rbinnext [1]),
    .B(\u_fifo.rptr_empty.rbinnext [0]),
    .Y(_239_)
  );
  sky130_fd_sc_hd__xnor2_1 _694_ (
    .A(\u_fifo.rptr_empty.rq2_wptr [1]),
    .B(\u_fifo.rptr_empty.rbinnext [2]),
    .Y(_240_)
  );
  sky130_fd_sc_hd__xnor2_1 _695_ (
    .A(_239_),
    .B(_240_),
    .Y(_241_)
  );
  sky130_fd_sc_hd__xor3_1 _696_ (
    .A(\u_fifo.rptr_empty.rq2_wptr [4]),
    .B(_223_),
    .C(_231_),
    .X(_242_)
  );
  sky130_fd_sc_hd__nand3b_1 _697_ (
    .A_N(_225_),
    .B(_241_),
    .C(_242_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__a211oi_1 _698_ (
    .A1(_235_),
    .A2(_236_),
    .B1(_238_),
    .C1(_243_),
    .Y(\u_fifo.rptr_empty.arempty_val )
  );
  sky130_fd_sc_hd__a21oi_1 _699_ (
    .A1(\u_fifo.fifomem.raddr [1]),
    .A2(\u_fifo.rptr_empty.rbinnext [0]),
    .B1(_239_),
    .Y(\u_fifo.rptr_empty.rgraynext [0])
  );
  sky130_fd_sc_hd__dfrtp_1 _700_ (
    .CLK(rclk_raw),
    .D(\u_fifo.rptr_empty.rgraynext [0]),
    .Q(\u_fifo.rptr [0]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _701_ (
    .CLK(rclk_raw),
    .D(\u_fifo.rptr_empty.rgraynext [1]),
    .Q(\u_fifo.rptr [1]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _702_ (
    .CLK(rclk_raw),
    .D(\u_fifo.rptr_empty.rgraynext [2]),
    .Q(\u_fifo.rptr [2]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _703_ (
    .CLK(rclk_raw),
    .D(\u_fifo.rptr_empty.rgraynext [3]),
    .Q(\u_fifo.rptr [3]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _704_ (
    .CLK(rclk_raw),
    .D(\u_fifo.rptr_empty.rbinnext [4]),
    .Q(\u_fifo.rptr [4]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _705_ (
    .CLK(rclk_raw),
    .D(\u_fifo.rptr_empty.rempty_val ),
    .Q(rempty_o),
    .SET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _706_ (
    .CLK(rclk_raw),
    .D(\u_fifo.rptr_empty.arempty_val ),
    .Q(arempty_o),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _707_ (
    .CLK(rclk_raw),
    .D(\u_fifo.rptr_empty.rbinnext [0]),
    .Q(\u_fifo.fifomem.raddr [0]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _708_ (
    .CLK(rclk_raw),
    .D(\u_fifo.rptr_empty.rbinnext [1]),
    .Q(\u_fifo.fifomem.raddr [1]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _709_ (
    .CLK(rclk_raw),
    .D(\u_fifo.rptr_empty.rbinnext [2]),
    .Q(\u_fifo.fifomem.raddr [2]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _710_ (
    .CLK(rclk_raw),
    .D(\u_fifo.rptr_empty.rbinnext [3]),
    .Q(\u_fifo.fifomem.raddr [3]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _711_ (
    .CLK(wclk_raw),
    .D(\u_fifo.rptr [0]),
    .Q(\u_fifo.sync_r2w.wq1_rptr [0]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _712_ (
    .CLK(wclk_raw),
    .D(\u_fifo.rptr [1]),
    .Q(\u_fifo.sync_r2w.wq1_rptr [1]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _713_ (
    .CLK(wclk_raw),
    .D(\u_fifo.rptr [2]),
    .Q(\u_fifo.sync_r2w.wq1_rptr [2]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _714_ (
    .CLK(wclk_raw),
    .D(\u_fifo.rptr [3]),
    .Q(\u_fifo.sync_r2w.wq1_rptr [3]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _715_ (
    .CLK(wclk_raw),
    .D(\u_fifo.rptr [4]),
    .Q(\u_fifo.sync_r2w.wq1_rptr [4]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _716_ (
    .CLK(wclk_raw),
    .D(\u_fifo.sync_r2w.wq1_rptr [0]),
    .Q(\u_fifo.sync_r2w.wq2_rptr [0]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _717_ (
    .CLK(wclk_raw),
    .D(\u_fifo.sync_r2w.wq1_rptr [1]),
    .Q(\u_fifo.sync_r2w.wq2_rptr [1]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _718_ (
    .CLK(wclk_raw),
    .D(\u_fifo.sync_r2w.wq1_rptr [2]),
    .Q(\u_fifo.sync_r2w.wq2_rptr [2]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _719_ (
    .CLK(wclk_raw),
    .D(\u_fifo.sync_r2w.wq1_rptr [3]),
    .Q(\u_fifo.sync_r2w.wq2_rptr [3]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _720_ (
    .CLK(wclk_raw),
    .D(\u_fifo.sync_r2w.wq1_rptr [4]),
    .Q(\u_fifo.sync_r2w.wq2_rptr [4]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _721_ (
    .CLK(rclk_raw),
    .D(\u_fifo.sync_w2r.wptr [0]),
    .Q(\u_fifo.sync_w2r.rq1_wptr [0]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _722_ (
    .CLK(rclk_raw),
    .D(\u_fifo.sync_w2r.wptr [1]),
    .Q(\u_fifo.sync_w2r.rq1_wptr [1]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _723_ (
    .CLK(rclk_raw),
    .D(\u_fifo.sync_w2r.wptr [2]),
    .Q(\u_fifo.sync_w2r.rq1_wptr [2]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _724_ (
    .CLK(rclk_raw),
    .D(\u_fifo.sync_w2r.wptr [3]),
    .Q(\u_fifo.sync_w2r.rq1_wptr [3]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _725_ (
    .CLK(rclk_raw),
    .D(\u_fifo.sync_w2r.wptr [4]),
    .Q(\u_fifo.sync_w2r.rq1_wptr [4]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _726_ (
    .CLK(rclk_raw),
    .D(\u_fifo.sync_w2r.rq1_wptr [0]),
    .Q(\u_fifo.rptr_empty.rq2_wptr [0]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _727_ (
    .CLK(rclk_raw),
    .D(\u_fifo.sync_w2r.rq1_wptr [1]),
    .Q(\u_fifo.rptr_empty.rq2_wptr [1]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _728_ (
    .CLK(rclk_raw),
    .D(\u_fifo.sync_w2r.rq1_wptr [2]),
    .Q(\u_fifo.rptr_empty.rq2_wptr [2]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _729_ (
    .CLK(rclk_raw),
    .D(\u_fifo.sync_w2r.rq1_wptr [3]),
    .Q(\u_fifo.rptr_empty.rq2_wptr [3]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _730_ (
    .CLK(rclk_raw),
    .D(\u_fifo.sync_w2r.rq1_wptr [4]),
    .Q(\u_fifo.rptr_empty.rq2_wptr [4]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__clkinv_1 _731_ (
    .A(\u_fifo.fifomem.waddr [2]),
    .Y(_244_)
  );
  sky130_fd_sc_hd__nor2b_1 _732_ (
    .A(wfull_o),
    .B_N(\u_fifo.fifomem.wclken ),
    .Y(_245_)
  );
  sky130_fd_sc_hd__nand3b_1 _733_ (
    .A_N(wfull_o),
    .B(\u_fifo.fifomem.wclken ),
    .C(\u_fifo.fifomem.waddr [0]),
    .Y(_246_)
  );
  sky130_fd_sc_hd__and4b_1 _734_ (
    .A_N(wfull_o),
    .B(\u_fifo.fifomem.wclken ),
    .C(\u_fifo.fifomem.waddr [0]),
    .D(\u_fifo.fifomem.waddr [1]),
    .X(_247_)
  );
  sky130_fd_sc_hd__a21oi_1 _735_ (
    .A1(\u_fifo.fifomem.waddr [2]),
    .A2(_247_),
    .B1(\u_fifo.fifomem.waddr [3]),
    .Y(_248_)
  );
  sky130_fd_sc_hd__xnor2_1 _736_ (
    .A(\u_fifo.sync_w2r.wptr [4]),
    .B(_248_),
    .Y(\u_fifo.wptr_full.wgraynext [3])
  );
  sky130_fd_sc_hd__xor2_1 _737_ (
    .A(\u_fifo.sync_r2w.wq2_rptr [3]),
    .B(\u_fifo.wptr_full.wgraynext [3]),
    .X(_249_)
  );
  sky130_fd_sc_hd__xor2_1 _738_ (
    .A(\u_fifo.fifomem.waddr [1]),
    .B(_246_),
    .X(_250_)
  );
  sky130_fd_sc_hd__clkinv_1 _739_ (
    .A(_250_),
    .Y(\u_fifo.wptr_full.wbinnext [1])
  );
  sky130_fd_sc_hd__nor2_1 _740_ (
    .A(\u_fifo.fifomem.waddr [2]),
    .B(_247_),
    .Y(_251_)
  );
  sky130_fd_sc_hd__xnor2_1 _741_ (
    .A(\u_fifo.fifomem.waddr [2]),
    .B(_247_),
    .Y(_252_)
  );
  sky130_fd_sc_hd__clkinv_1 _742_ (
    .A(_252_),
    .Y(\u_fifo.wptr_full.wbinnext [2])
  );
  sky130_fd_sc_hd__xor2_1 _743_ (
    .A(\u_fifo.sync_r2w.wq2_rptr [1]),
    .B(_252_),
    .X(_253_)
  );
  sky130_fd_sc_hd__xnor2_1 _744_ (
    .A(\u_fifo.wptr_full.wbinnext [1]),
    .B(_252_),
    .Y(\u_fifo.wptr_full.wgraynext [1])
  );
  sky130_fd_sc_hd__xnor2_1 _745_ (
    .A(_250_),
    .B(_253_),
    .Y(_254_)
  );
  sky130_fd_sc_hd__and3_1 _746_ (
    .A(\u_fifo.fifomem.waddr [2]),
    .B(\u_fifo.fifomem.waddr [3]),
    .C(_247_),
    .X(_255_)
  );
  sky130_fd_sc_hd__xor2_1 _747_ (
    .A(\u_fifo.sync_w2r.wptr [4]),
    .B(_255_),
    .X(\u_fifo.wptr_full.wbinnext [4])
  );
  sky130_fd_sc_hd__xnor3_1 _748_ (
    .A(\u_fifo.sync_r2w.wq2_rptr [4]),
    .B(\u_fifo.sync_w2r.wptr [4]),
    .C(_255_),
    .X(_256_)
  );
  sky130_fd_sc_hd__xnor2_1 _749_ (
    .A(\u_fifo.fifomem.waddr [3]),
    .B(_251_),
    .Y(\u_fifo.wptr_full.wgraynext [2])
  );
  sky130_fd_sc_hd__xor2_1 _750_ (
    .A(\u_fifo.sync_r2w.wq2_rptr [2]),
    .B(\u_fifo.wptr_full.wgraynext [2]),
    .X(_257_)
  );
  sky130_fd_sc_hd__xnor2_1 _751_ (
    .A(\u_fifo.fifomem.waddr [0]),
    .B(_245_),
    .Y(_258_)
  );
  sky130_fd_sc_hd__clkinv_1 _752_ (
    .A(_258_),
    .Y(\u_fifo.wptr_full.wbinnext [0])
  );
  sky130_fd_sc_hd__xnor2_1 _753_ (
    .A(\u_fifo.sync_r2w.wq2_rptr [0]),
    .B(\u_fifo.wptr_full.wbinnext [1]),
    .Y(_259_)
  );
  sky130_fd_sc_hd__xnor2_1 _754_ (
    .A(_258_),
    .B(_259_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__nand3_1 _755_ (
    .A(_249_),
    .B(_254_),
    .C(_260_),
    .Y(_261_)
  );
  sky130_fd_sc_hd__nor3_1 _756_ (
    .A(_256_),
    .B(_257_),
    .C(_261_),
    .Y(\u_fifo.wptr_full.wfull_val )
  );
  sky130_fd_sc_hd__nor2_1 _757_ (
    .A(_250_),
    .B(_258_),
    .Y(_262_)
  );
  sky130_fd_sc_hd__nand4_1 _758_ (
    .A(\u_fifo.fifomem.waddr [2]),
    .B(\u_fifo.fifomem.waddr [3]),
    .C(\u_fifo.wptr_full.wbinnext [1]),
    .D(\u_fifo.wptr_full.wbinnext [0]),
    .Y(_263_)
  );
  sky130_fd_sc_hd__nor2_1 _759_ (
    .A(\u_fifo.wptr_full.wbinnext [1]),
    .B(\u_fifo.wptr_full.wbinnext [0]),
    .Y(_264_)
  );
  sky130_fd_sc_hd__nand2_1 _760_ (
    .A(_250_),
    .B(_258_),
    .Y(_265_)
  );
  sky130_fd_sc_hd__a21oi_1 _761_ (
    .A1(_253_),
    .A2(_265_),
    .B1(_259_),
    .Y(_266_)
  );
  sky130_fd_sc_hd__xor2_1 _762_ (
    .A(_256_),
    .B(_263_),
    .X(_267_)
  );
  sky130_fd_sc_hd__o211ai_1 _763_ (
    .A1(_253_),
    .A2(_265_),
    .B1(_266_),
    .C1(_267_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__nor2_1 _764_ (
    .A(_248_),
    .B(_255_),
    .Y(\u_fifo.wptr_full.wbinnext [3])
  );
  sky130_fd_sc_hd__o32a_1 _765_ (
    .A1(_244_),
    .A2(_250_),
    .A3(_258_),
    .B1(_255_),
    .B2(_248_),
    .X(_269_)
  );
  sky130_fd_sc_hd__xnor2_1 _766_ (
    .A(\u_fifo.sync_r2w.wq2_rptr [3]),
    .B(\u_fifo.wptr_full.wbinnext [4]),
    .Y(_270_)
  );
  sky130_fd_sc_hd__xnor2_1 _767_ (
    .A(_269_),
    .B(_270_),
    .Y(_271_)
  );
  sky130_fd_sc_hd__o21ai_0 _768_ (
    .A1(_250_),
    .A2(_258_),
    .B1(_252_),
    .Y(_272_)
  );
  sky130_fd_sc_hd__mux2i_1 _769_ (
    .A0(_269_),
    .A1(\u_fifo.wptr_full.wbinnext [3]),
    .S(_272_),
    .Y(_273_)
  );
  sky130_fd_sc_hd__xor2_1 _770_ (
    .A(\u_fifo.sync_r2w.wq2_rptr [2]),
    .B(_273_),
    .X(_274_)
  );
  sky130_fd_sc_hd__nor3_1 _771_ (
    .A(_268_),
    .B(_271_),
    .C(_274_),
    .Y(\u_fifo.wptr_full.awfull_val )
  );
  sky130_fd_sc_hd__nor2_1 _772_ (
    .A(_262_),
    .B(_264_),
    .Y(\u_fifo.wptr_full.wgraynext [0])
  );
  sky130_fd_sc_hd__dfrtp_1 _773_ (
    .CLK(wclk_raw),
    .D(\u_fifo.wptr_full.wbinnext [0]),
    .Q(\u_fifo.fifomem.waddr [0]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _774_ (
    .CLK(wclk_raw),
    .D(\u_fifo.wptr_full.wbinnext [1]),
    .Q(\u_fifo.fifomem.waddr [1]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _775_ (
    .CLK(wclk_raw),
    .D(\u_fifo.wptr_full.wbinnext [2]),
    .Q(\u_fifo.fifomem.waddr [2]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _776_ (
    .CLK(wclk_raw),
    .D(\u_fifo.wptr_full.wbinnext [3]),
    .Q(\u_fifo.fifomem.waddr [3]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _777_ (
    .CLK(wclk_raw),
    .D(\u_fifo.wptr_full.wgraynext [0]),
    .Q(\u_fifo.sync_w2r.wptr [0]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _778_ (
    .CLK(wclk_raw),
    .D(\u_fifo.wptr_full.wgraynext [1]),
    .Q(\u_fifo.sync_w2r.wptr [1]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _779_ (
    .CLK(wclk_raw),
    .D(\u_fifo.wptr_full.wgraynext [2]),
    .Q(\u_fifo.sync_w2r.wptr [2]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _780_ (
    .CLK(wclk_raw),
    .D(\u_fifo.wptr_full.wgraynext [3]),
    .Q(\u_fifo.sync_w2r.wptr [3]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _781_ (
    .CLK(wclk_raw),
    .D(\u_fifo.wptr_full.wbinnext [4]),
    .Q(\u_fifo.sync_w2r.wptr [4]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _782_ (
    .CLK(wclk_raw),
    .D(\u_fifo.wptr_full.wfull_val ),
    .Q(wfull_o),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _783_ (
    .CLK(wclk_raw),
    .D(\u_fifo.wptr_full.awfull_val ),
    .Q(awfull_o),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__clkinv_1 _784_ (
    .A(prod_active),
    .Y(_279_)
  );
  sky130_fd_sc_hd__clkinv_1 _785_ (
    .A(\u_prod.burst_cnt [1]),
    .Y(_280_)
  );
  sky130_fd_sc_hd__nor2b_1 _786_ (
    .A(wfull_o),
    .B_N(prod_active),
    .Y(_278_)
  );
  sky130_fd_sc_hd__nand3b_1 _787_ (
    .A_N(wfull_o),
    .B(w_event),
    .C(_279_),
    .Y(_281_)
  );
  sky130_fd_sc_hd__nand3_1 _788_ (
    .A(\u_prod.burst_cnt [0]),
    .B(\u_prod.burst_cnt [1]),
    .C(\u_prod.burst_cnt [2]),
    .Y(_282_)
  );
  sky130_fd_sc_hd__nand4_1 _789_ (
    .A(\u_prod.burst_cnt [0]),
    .B(\u_prod.burst_cnt [1]),
    .C(\u_prod.burst_cnt [2]),
    .D(\u_prod.burst_cnt [3]),
    .Y(_283_)
  );
  sky130_fd_sc_hd__o21ai_0 _790_ (
    .A1(\u_prod.burst_cnt [4]),
    .A2(_283_),
    .B1(_278_),
    .Y(_284_)
  );
  sky130_fd_sc_hd__nand2_1 _791_ (
    .A(_281_),
    .B(_284_),
    .Y(_276_)
  );
  sky130_fd_sc_hd__o211ai_1 _792_ (
    .A1(\u_prod.burst_cnt [4]),
    .A2(_283_),
    .B1(_278_),
    .C1(\u_prod.burst_cnt [0]),
    .Y(_285_)
  );
  sky130_fd_sc_hd__nand3_1 _793_ (
    .A(\u_prod.burst_cnt [0]),
    .B(_281_),
    .C(_284_),
    .Y(_286_)
  );
  sky130_fd_sc_hd__o21ai_0 _794_ (
    .A1(\u_prod.burst_cnt [0]),
    .A2(_284_),
    .B1(_286_),
    .Y(_275_[0])
  );
  sky130_fd_sc_hd__nand2_1 _795_ (
    .A(\u_prod.burst_cnt [1]),
    .B(_281_),
    .Y(_287_)
  );
  sky130_fd_sc_hd__nor2_1 _796_ (
    .A(_280_),
    .B(_285_),
    .Y(_288_)
  );
  sky130_fd_sc_hd__a21oi_1 _797_ (
    .A1(_285_),
    .A2(_287_),
    .B1(_288_),
    .Y(_275_[1])
  );
  sky130_fd_sc_hd__nand2_1 _798_ (
    .A(\u_prod.burst_cnt [2]),
    .B(_281_),
    .Y(_289_)
  );
  sky130_fd_sc_hd__mux2i_1 _799_ (
    .A0(_289_),
    .A1(\u_prod.burst_cnt [2]),
    .S(_288_),
    .Y(_275_[2])
  );
  sky130_fd_sc_hd__o211ai_1 _800_ (
    .A1(_282_),
    .A2(_284_),
    .B1(\u_prod.burst_cnt [3]),
    .C1(_281_),
    .Y(_290_)
  );
  sky130_fd_sc_hd__o31ai_1 _801_ (
    .A1(\u_prod.burst_cnt [3]),
    .A2(_282_),
    .A3(_284_),
    .B1(_290_),
    .Y(_275_[3])
  );
  sky130_fd_sc_hd__o311a_1 _802_ (
    .A1(wfull_o),
    .A2(_279_),
    .A3(_283_),
    .B1(_281_),
    .C1(\u_prod.burst_cnt [4]),
    .X(_275_[4])
  );
  sky130_fd_sc_hd__xor2_1 _803_ (
    .A(\u_fifo.fifomem.wdata [0]),
    .B(_278_),
    .X(_277_[0])
  );
  sky130_fd_sc_hd__and4b_1 _804_ (
    .A_N(wfull_o),
    .B(prod_active),
    .C(\u_fifo.fifomem.wdata [0]),
    .D(\u_fifo.fifomem.wdata [1]),
    .X(_291_)
  );
  sky130_fd_sc_hd__a21oi_1 _805_ (
    .A1(\u_fifo.fifomem.wdata [0]),
    .A2(_278_),
    .B1(\u_fifo.fifomem.wdata [1]),
    .Y(_292_)
  );
  sky130_fd_sc_hd__nor2_1 _806_ (
    .A(_291_),
    .B(_292_),
    .Y(_277_[1])
  );
  sky130_fd_sc_hd__xor2_1 _807_ (
    .A(\u_fifo.fifomem.wdata [2]),
    .B(_291_),
    .X(_277_[2])
  );
  sky130_fd_sc_hd__a21oi_1 _808_ (
    .A1(\u_fifo.fifomem.wdata [2]),
    .A2(_291_),
    .B1(\u_fifo.fifomem.wdata [3]),
    .Y(_293_)
  );
  sky130_fd_sc_hd__and3_1 _809_ (
    .A(\u_fifo.fifomem.wdata [2]),
    .B(\u_fifo.fifomem.wdata [3]),
    .C(_291_),
    .X(_294_)
  );
  sky130_fd_sc_hd__nor2_1 _810_ (
    .A(_293_),
    .B(_294_),
    .Y(_277_[3])
  );
  sky130_fd_sc_hd__nand2_1 _811_ (
    .A(\u_fifo.fifomem.wdata [4]),
    .B(_294_),
    .Y(_295_)
  );
  sky130_fd_sc_hd__xor2_1 _812_ (
    .A(\u_fifo.fifomem.wdata [4]),
    .B(_294_),
    .X(_277_[4])
  );
  sky130_fd_sc_hd__nand3_1 _813_ (
    .A(\u_fifo.fifomem.wdata [4]),
    .B(\u_fifo.fifomem.wdata [5]),
    .C(_294_),
    .Y(_296_)
  );
  sky130_fd_sc_hd__xnor2_1 _814_ (
    .A(\u_fifo.fifomem.wdata [5]),
    .B(_295_),
    .Y(_277_[5])
  );
  sky130_fd_sc_hd__nand4_1 _815_ (
    .A(\u_fifo.fifomem.wdata [4]),
    .B(\u_fifo.fifomem.wdata [5]),
    .C(\u_fifo.fifomem.wdata [6]),
    .D(_294_),
    .Y(_297_)
  );
  sky130_fd_sc_hd__xnor2_1 _816_ (
    .A(\u_fifo.fifomem.wdata [6]),
    .B(_296_),
    .Y(_277_[6])
  );
  sky130_fd_sc_hd__xnor2_1 _817_ (
    .A(\u_fifo.fifomem.wdata [7]),
    .B(_297_),
    .Y(_277_[7])
  );
  sky130_fd_sc_hd__dfrtp_1 _818_ (
    .CLK(wclk_raw),
    .D(_278_),
    .Q(\u_fifo.fifomem.wclken ),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _819_ (
    .CLK(wclk_raw),
    .D(_275_[0]),
    .Q(\u_prod.burst_cnt [0]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _820_ (
    .CLK(wclk_raw),
    .D(_275_[1]),
    .Q(\u_prod.burst_cnt [1]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _821_ (
    .CLK(wclk_raw),
    .D(_275_[2]),
    .Q(\u_prod.burst_cnt [2]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _822_ (
    .CLK(wclk_raw),
    .D(_275_[3]),
    .Q(\u_prod.burst_cnt [3]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _823_ (
    .CLK(wclk_raw),
    .D(_275_[4]),
    .Q(\u_prod.burst_cnt [4]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _824_ (
    .CLK(wclk_raw),
    .D(_276_),
    .Q(prod_active),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _825_ (
    .CLK(wclk_raw),
    .D(_277_[0]),
    .Q(\u_fifo.fifomem.wdata [0]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _826_ (
    .CLK(wclk_raw),
    .D(_277_[1]),
    .Q(\u_fifo.fifomem.wdata [1]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _827_ (
    .CLK(wclk_raw),
    .D(_277_[2]),
    .Q(\u_fifo.fifomem.wdata [2]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _828_ (
    .CLK(wclk_raw),
    .D(_277_[3]),
    .Q(\u_fifo.fifomem.wdata [3]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _829_ (
    .CLK(wclk_raw),
    .D(_277_[4]),
    .Q(\u_fifo.fifomem.wdata [4]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _830_ (
    .CLK(wclk_raw),
    .D(_277_[5]),
    .Q(\u_fifo.fifomem.wdata [5]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _831_ (
    .CLK(wclk_raw),
    .D(_277_[6]),
    .Q(\u_fifo.fifomem.wdata [6]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _832_ (
    .CLK(wclk_raw),
    .D(_277_[7]),
    .Q(\u_fifo.fifomem.wdata [7]),
    .RESET_B(wrst_n)
  );
  assign \u_fifo.wptr_full.wgraynext [4] = \u_fifo.wptr_full.wbinnext [4];
  assign \u_fifo.rptr_empty.rgraynext [4] = \u_fifo.rptr_empty.rbinnext [4];
endmodule
